"""Persistence + dynamic registration for user-built strategies (FB-AP-XXX strategy builder).

Each user-built strategy is saved as a sidecar JSON file (mirrors
``app/runtime/asset_strategy_selection.py``'s pattern) under
``data/custom_strategies/<id>.json``, and — the key integration trick — is also registered
into :mod:`strategies.registry` as an ordinary ``StrategyDescriptor`` with key
``"custom:<id>"``, whose sole tunable parameter (``rule_spec``) carries the strategy's JSON
spec as a string.

This means the *entire* existing pipeline (the registry, ``backtesting/nautilus_backtest.py``,
``app.runtime.asset_strategy_selection``, the Asset page's strategy picker) handles
user-built strategies automatically, with no special-casing: to them, ``custom:<id>`` looks
exactly like ``ema_cross`` — just another catalogue entry resolving to a ``Strategy``/
``StrategyConfig`` pair (in this case, the single shared
:class:`strategies.rule_based_strategy.RuleBasedStrategy`).
"""

from __future__ import annotations

import json
import os
import re
from datetime import UTC, datetime
from pathlib import Path

from app.runtime import tenant_context
from app.runtime import user_data_paths as user_paths
from strategies.registry import StrategyDescriptor, StrategyParam, register_or_replace, unregister
from strategies.rule_spec import RuleSpecError, RuleStrategySpec

_DEFAULT_DIR = Path(os.getenv("NM_CUSTOM_STRATEGIES_DIR", "data/custom_strategies"))

_KEY_PREFIX = "custom:"


def _multi_tenant() -> bool:
    return os.getenv("NM_MULTI_TENANT_DATA_SCOPING", "").strip().lower() in ("1", "true", "yes")


def custom_strategies_dir() -> Path:
    if _multi_tenant():
        return user_paths.custom_strategies_dir()
    return _DEFAULT_DIR


def _slugify(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", name.strip().lower()).strip("_")
    return slug or "strategy"


def _path(strategy_id: str) -> Path:
    sid = strategy_id.strip()
    if not sid or "/" in sid or "\\" in sid or sid.startswith("."):
        raise ValueError("invalid custom strategy id")
    return custom_strategies_dir() / f"{sid}.json"


def registry_key(strategy_id: str) -> str:
    """Catalogue key for a custom strategy — namespaced per tenant when multi-tenant scoping
    is on, so two users' strategies of the same id can't collide in the shared registry."""
    if _multi_tenant():
        uid = tenant_context.get_current_user_id()
        if uid is not None:
            return f"{_KEY_PREFIX}u{uid}:{strategy_id}"
    return f"{_KEY_PREFIX}{strategy_id}"


def _descriptor_for(strategy_id: str, spec: RuleStrategySpec) -> StrategyDescriptor:
    return StrategyDescriptor(
        key=registry_key(strategy_id),
        name=spec.name,
        description=spec.explain(),
        strategy_path="strategies.rule_based_strategy:RuleBasedStrategy",
        config_path="strategies.rule_based_strategy:RuleBasedStrategyConfig",
        params=(
            StrategyParam(
                name="rule_spec",
                kind="string",
                default=spec.to_json(),
                description="JSON-encoded strategy rules (generated by the strategy builder)",
            ),
        ),
    )


def _new_id(name: str) -> str:
    base = _slugify(name)
    candidate = base
    n = 2
    while _path(candidate).exists():
        candidate = f"{base}_{n}"
        n += 1
    return candidate


def list_custom_strategies() -> list[dict]:
    """All saved custom strategies, newest-updated first."""
    d = custom_strategies_dir()
    if not d.is_dir():
        return []
    out: list[dict] = []
    for p in d.glob("*.json"):
        record = _read(p)
        if record is not None:
            out.append(record)
    out.sort(key=lambda r: r.get("updated_at", ""), reverse=True)
    return out


def get_custom_strategy(strategy_id: str) -> dict | None:
    return _read(_path(strategy_id))


def _read(path: Path) -> dict | None:
    if not path.is_file():
        return None
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None
    if not isinstance(raw, dict) or "id" not in raw or "spec" not in raw:
        return None
    return raw


def save_custom_strategy(spec: RuleStrategySpec, *, strategy_id: str | None = None) -> dict:
    """Validate, persist, and (re-)register a user-built strategy. Returns its stored record.

    If ``strategy_id`` is ``None`` a fresh id is derived from the strategy's name; otherwise
    the existing record at that id is overwritten (edit-and-resave).
    """
    spec.validate()
    now = datetime.now(tz=UTC).isoformat().replace("+00:00", "Z")
    sid = strategy_id.strip() if strategy_id else _new_id(spec.name)
    existing = get_custom_strategy(sid)
    record = {
        "id": sid,
        "spec": spec.to_dict(),
        "created_at": existing["created_at"] if existing else now,
        "updated_at": now,
    }

    p = _path(sid)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")

    register_or_replace(_descriptor_for(sid, spec))
    return record


def delete_custom_strategy(strategy_id: str) -> bool:
    p = _path(strategy_id)
    if not p.is_file():
        return False
    p.unlink()
    unregister(registry_key(strategy_id))
    return True


def register_custom_strategies() -> int:
    """Load every saved custom strategy from disk into the live registry.

    Call once at process start (mirrors how the registry module self-populates its built-in
    entries at import time) so user-built strategies survive a restart. Returns the count
    registered; corrupt/invalid records are skipped rather than raising.
    """
    count = 0
    for record in list_custom_strategies():
        try:
            spec = RuleStrategySpec.from_dict(record["spec"])
            spec.validate()
        except (RuleSpecError, KeyError, TypeError, ValueError):
            continue
        register_or_replace(_descriptor_for(record["id"], spec))
        count += 1
    return count
