-- The sixteen-gate stack made durable (SPEC §12.3, §12.7; plan 2.14, 2.15, 5.3, 5.5).
--
-- Three things land here, and each one exists because a signal or a gate cannot be
-- computed without it:
--
--   1. `mlops.gate_verdict` — the tenant-scoped, append-only record of every gate
--      decision, carrying the `profile_id` it was judged under. Without this row
--      "gate pass rate by profile" (§16.2) has nothing to read, and a verdict's
--      threshold is only recoverable from whatever code happened to be deployed.
--      The Set J `backtest_gate_verdicts` table stays: it is the five-stage funnel's
--      own record, keyed by experiment and unaware of tenants or profiles.
--
--   2. The `paper_v1` profile (ADR-P2-14). `strict_v1` is untouched — profiles are
--      immutable, so a different purpose is a different profile, never an edit.
--      `paper_v1` authorises paper deployment and *cannot authorise capital*, which
--      is a column here rather than a convention.
--
--   3. `mlops.campaign.platform_seed` (§12.7, ADR-P2-18) — generated by the
--      database, never by a caller, and unreadable by `agent_role`. Gates 11-13 and
--      the ASHA top-3 re-evaluation draw from it, so an agent that could read it
--      could tune against it.

-- ── gate verdicts ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS mlops.gate_verdict (
  verdict_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           TEXT NOT NULL,
  -- What was judged. At least one of these locates it.
  experiment_id       TEXT,
  trial_id            UUID REFERENCES mlops.trial(trial_id),
  campaign_id         UUID REFERENCES mlops.campaign(campaign_id),
  -- The bar it was judged against. A verdict without its profile is not a verdict:
  -- "passed" means nothing unless you can say passed *what*.
  profile_id          TEXT NOT NULL REFERENCES mlops.gate_profile(profile_id),
  gate_no             INT  NOT NULL CHECK (gate_no BETWEEN 1 AND 16),
  gate_name           TEXT NOT NULL,
  passed              BOOLEAN NOT NULL,
  -- The number that decided it and the bar it cleared or missed, so a later
  -- threshold change can be audited against verdicts already on record.
  statistic           DOUBLE PRECISION,
  threshold           DOUBLE PRECISION,
  detail              TEXT NOT NULL,
  evidence            JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- INV-3: significance is never naked.
  n_eff               DOUBLE PRECISION,
  trial_count_at_eval BIGINT,
  decided_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (experiment_id IS NOT NULL OR trial_id IS NOT NULL),
  CONSTRAINT chk_gate_significance_never_naked CHECK (
    gate_no NOT IN (8, 14) OR (n_eff IS NOT NULL AND trial_count_at_eval IS NOT NULL)
  )
);
CREATE INDEX IF NOT EXISTS idx_gate_verdict_recent
  ON mlops.gate_verdict (tenant_id, profile_id, decided_at DESC);
CREATE INDEX IF NOT EXISTS idx_gate_verdict_subject
  ON mlops.gate_verdict (tenant_id, experiment_id, gate_no);

DROP TRIGGER IF EXISTS trg_gate_verdict_immutable ON mlops.gate_verdict;
CREATE TRIGGER trg_gate_verdict_immutable BEFORE UPDATE OR DELETE ON mlops.gate_verdict
  FOR EACH ROW EXECUTE FUNCTION mlops.refuse_mutation();

ALTER TABLE mlops.gate_verdict ENABLE ROW LEVEL SECURITY;
ALTER TABLE mlops.gate_verdict FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON mlops.gate_verdict;
CREATE POLICY tenant_isolation ON mlops.gate_verdict
  USING (tenant_id = current_setting('app.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true));

GRANT SELECT, INSERT ON mlops.gate_verdict TO app_role;
REVOKE UPDATE, DELETE, TRUNCATE ON mlops.gate_verdict FROM app_role;
-- Agents read verdicts; they hold nothing on the thresholds those verdicts used.
GRANT SELECT ON mlops.gate_verdict TO agent_role;

-- ── per-asset-class gate facts ────────────────────────────────────────────────
--
-- Gate 10's factor battery and Gate 11's crisis windows are *per asset class*, not
-- per-profile scalars (ADR-P2-15, P2-16). They live in their own immutable table
-- rather than inside the thresholds blob, so `strict_v1`'s stored thresholds stay
-- byte-identical to what migration 0043 wrote and every verdict recorded under it
-- still means exactly what it meant.

CREATE TABLE IF NOT EXISTS mlops.gate_profile_asset_class (
  profile_id     TEXT NOT NULL REFERENCES mlops.gate_profile(profile_id),
  asset_class    TEXT NOT NULL,
  -- Gate 10. A regression against factors that do not exist for the asset is not
  -- attribution, so the battery is declared where the asset class is known.
  factor_battery TEXT[] NOT NULL CHECK (cardinality(factor_battery) >= 1),
  -- Gate 11. Facts about the world, not model output, so they belong on the
  -- immutable profile rather than in a regime model's parameters.
  crisis_windows JSONB NOT NULL,
  PRIMARY KEY (profile_id, asset_class)
);
DROP TRIGGER IF EXISTS trg_gate_profile_ac_immutable ON mlops.gate_profile_asset_class;
CREATE TRIGGER trg_gate_profile_ac_immutable
  BEFORE UPDATE OR DELETE ON mlops.gate_profile_asset_class
  FOR EACH ROW EXECUTE FUNCTION mlops.refuse_mutation();

-- ── a profile may or may not authorise capital ────────────────────────────────
-- Adding a column with a constant default does not rewrite rows and does not fire
-- the row-level immutability trigger, so `strict_v1` is not touched by this.
ALTER TABLE mlops.gate_profile
  ADD COLUMN IF NOT EXISTS authorises_capital BOOLEAN NOT NULL DEFAULT TRUE;

-- ── paper_v1 ──────────────────────────────────────────────────────────────────
--
-- `strict_v1` minus Gate 9's five-year calendar floor and minus Gate 16. Every
-- other threshold is identical, byte for byte, because the point of a second
-- profile is to change one thing for one purpose — not to become a softer default.
--
-- Why it exists (ADR-P2-14, OQ-13): a platform whose history is months old cannot
-- pass a five-year floor, and P-01 says that floor is right. But paper is where the
-- years are honestly accumulated, and a strategy that cannot reach paper never
-- accumulates them. `paper_v1` cannot authorise capital, so what it risks is bounded
-- to the thing it is for.
INSERT INTO mlops.gate_profile (profile_id, thresholds, supersedes, created_by, authorises_capital)
VALUES ('paper_v1', '{
  "preregistration_required": true,
  "leakage_suite_pass_rate": 1.0,
  "min_breakeven_cost_multiple": 3.0,
  "max_capacity_fraction_at_half_sharpe": 0.20,
  "adv_soft": 0.05, "adv_hard": 0.10,
  "cpcv_p05_sharpe_gt": 0.0,
  "walk_forward_sharpe_gt": 0.0, "walk_forward_min_regimes": 3,
  "pbo_lt": 0.20,
  "dsr_gte": 0.95,
  "min_track_record_years": 0.0, "min_independent_events": 300,
  "alpha_t_stat_gte": 3.0, "factor_r2_lt": 0.7,
  "max_single_regime_pnl_share": 0.50,
  "max_single_instrument_pnl_share": 0.20,
  "bootstrap_p05_sharpe_gt": 0.0,
  "romano_wolf_p_lt": 0.05,
  "paper_signal_match_gte": 0.99, "paper_slippage_ratio_lte": 1.5,
  "paper_turnover_tolerance": 0.20, "paper_model_rejects_max": 0,
  "capital_ramp": []
}'::jsonb, 'strict_v1', 'platform', FALSE)
ON CONFLICT (profile_id) DO NOTHING;

-- Crypto is what this platform trades; the equity battery is declared so that the
-- day an equity source is live the gate has a definition rather than a TODO.
-- Crisis windows are the dated episodes the reference names, filtered to those the
-- asset class actually lived through.
INSERT INTO mlops.gate_profile_asset_class (profile_id, asset_class, factor_battery, crisis_windows)
VALUES
  ('strict_v1', 'crypto',
   ARRAY['cmkt','csmb','cmom','ccarry'],
   '[{"label":"covid_crash","from":"2020-03-01","to":"2020-04-01"},
     {"label":"may_2021_deleveraging","from":"2021-05-01","to":"2021-06-01"},
     {"label":"terra_luna","from":"2022-05-01","to":"2022-06-01"},
     {"label":"three_arrows","from":"2022-06-01","to":"2022-07-15"},
     {"label":"ftx","from":"2022-11-01","to":"2022-12-01"},
     {"label":"banking_stress","from":"2023-03-01","to":"2023-04-01"},
     {"label":"yen_carry_unwind","from":"2024-08-01","to":"2024-08-15"},
     {"label":"tariff_vol_2025","from":"2025-01-01","to":"2025-04-01"}]'::jsonb),
  ('strict_v1', 'equity',
   ARRAY['mkt_rf','smb','hml','rmw','cma','mom','str','bab','qmj'],
   '[{"label":"gfc","from":"2008-09-01","to":"2009-04-01"},
     {"label":"flash_crash","from":"2010-05-01","to":"2010-06-01"},
     {"label":"us_downgrade","from":"2011-08-01","to":"2011-10-01"},
     {"label":"china_devaluation","from":"2015-08-01","to":"2015-09-15"},
     {"label":"volmageddon","from":"2018-02-01","to":"2018-03-01"},
     {"label":"q4_2018","from":"2018-10-01","to":"2019-01-01"},
     {"label":"covid_crash","from":"2020-02-15","to":"2020-04-01"},
     {"label":"rates_inflation_bear","from":"2022-01-01","to":"2022-11-01"},
     {"label":"banking_stress","from":"2023-03-01","to":"2023-04-01"},
     {"label":"yen_carry_unwind","from":"2024-08-01","to":"2024-08-15"}]'::jsonb)
ON CONFLICT (profile_id, asset_class) DO NOTHING;

-- paper_v1 judges the same worlds as strict_v1.
INSERT INTO mlops.gate_profile_asset_class (profile_id, asset_class, factor_battery, crisis_windows)
SELECT 'paper_v1', asset_class, factor_battery, crisis_windows
  FROM mlops.gate_profile_asset_class WHERE profile_id = 'strict_v1'
ON CONFLICT (profile_id, asset_class) DO NOTHING;

GRANT SELECT ON mlops.gate_profile_asset_class TO app_role, internal_ml_role, agent_role;

-- ── the platform-held seed (§12.7) ────────────────────────────────────────────
--
-- Generated by the database, so no code path can supply a predictable one, and
-- re-drawn per campaign because a seed reused across campaigns is a seed that can
-- be learned.
ALTER TABLE mlops.campaign
  ADD COLUMN IF NOT EXISTS platform_seed BIGINT NOT NULL
  DEFAULT (floor(random() * 9007199254740991))::bigint;

-- Agents may read their campaigns — but not this column. A table-level grant cannot
-- be narrowed by a column-level revoke, so the table grant is withdrawn and the
-- columns are granted back one by one. The omission is the mechanism.
REVOKE SELECT ON mlops.campaign FROM agent_role;
GRANT SELECT (campaign_id, slug, tenant_id, hypothesis, objective, benchmark,
              delta_practical, budget, exploration_floor, gates_profile,
              preference_vector, search_space, created_by, created_at)
  ON mlops.campaign TO agent_role;
