#!/usr/bin/env python3
"""One-off helper: regenerate docs/QUEUE_STACK.csv with self-contained agent_task columns.
   Run from repo root: python scripts/generate_queue_stack.py"""
from __future__ import annotations

import csv
from pathlib import Path

ROWS: list[dict[str, str]] = [
    {
        "stack_order": "1",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-DOC",
        "id": "FB-AUD-001",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Production API hardening (docs): TLS firewall API key CORS",
        "agent_task": "COMPLETED. Delivered: README and RUNBOOKS subsections for production control plane — TLS, firewall, NM_CONTROL_PLANE_API_KEY or session auth, and restricting CORS when API is not localhost-only. Traceability: audit DOC-A1.",
        "affected_files": "README.md|docs/RUNBOOKS.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "DOC-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "2",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-DOC",
        "id": "FB-AUD-002",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Streamlit route guard docs",
        "agent_task": "COMPLETED. Delivered: README + RUNBOOKS + streamlit_util docstrings for when to set NM_STREAMLIT_ROUTE_GUARD_ENABLED, session env alignment, and NM_CONTROL_PLANE_API_KEY bypass for automation. Traceability: audit DOC-A2.",
        "affected_files": "README.md|docs/RUNBOOKS.MD|control_plane/streamlit_util.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "DOC-A2",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "3",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-OPS",
        "id": "FB-AUD-003",
        "kind": "platform",
        "status": "Open",
        "summary_one_line": "Startup warning when API key unset and bind non-loopback",
        "agent_task": "Goal: reduce misconfiguration risk when the control plane is reachable beyond localhost. Requirement: when NM_CONTROL_PLANE_API_KEY (or equivalent control_plane_api_key setting) is unset AND the HTTP bind address is not loopback-only (not 127.0.0.1 / ::1), emit a clear WARNING at startup (log and/or stderr). When key is set OR bind is loopback-only, do not spam warnings. Acceptance: reproduce with bind 0.0.0.0 and no key — warning appears; document one-line pointer in RUNBOOKS under production exposure. Traceability: audit OPS-A1.",
        "affected_files": "control_plane/api.py|docs/RUNBOOKS.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|docs/RUNBOOKS.MD",
        "audit_id": "OPS-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "4",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-OPS",
        "id": "FB-AUD-004",
        "kind": "platform",
        "status": "Open",
        "summary_one_line": "Optional rate limiting for control_plane public exposure",
        "agent_task": "Goal: basic abuse protection when API is exposed. Either (A) add optional middleware rate limiting in control_plane behind an env flag, OR (B) document a production-grade reverse-proxy recipe (Caddy/Nginx) with rate limiting and link from README/RUNBOOKS. Do not break local dev defaults. Acceptance: operators have a clear path for public deployments. Traceability: audit OPS-A2.",
        "affected_files": "control_plane/api.py|docs/RUNBOOKS.MD|infra/",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "OPS-A2",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "5",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-QA",
        "id": "FB-AUD-005",
        "kind": "tech_debt",
        "status": "Open",
        "summary_one_line": "Exception logging pass live_service.py",
        "agent_task": "Goal: debuggability of the live decision loop. In app/runtime/live_service.py, audit broad exception handlers; ensure each logs with symbol and/or correlation/job context (no silent swallow). Acceptance: ruff/pytest pass; no secret leakage in logs. Traceability: audit QA-A1.",
        "affected_files": "app/runtime/live_service.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "QA-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "6",
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-QA",
        "id": "FB-AUD-006",
        "kind": "tech_debt",
        "status": "Open",
        "summary_one_line": "Exception logging pass asset_page streamlit_util",
        "agent_task": "Goal: user-visible errors remain helpful. In control_plane/asset_page.py and control_plane/streamlit_util.py, improve exception paths so operators see actionable messages and logs include context. Acceptance: Streamlit still works; pytest pass. Traceability: audit QA-A2.",
        "affected_files": "control_plane/asset_page.py|control_plane/streamlit_util.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "QA-A2",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "7",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-CODE",
        "id": "FB-AUD-007",
        "kind": "change",
        "status": "Open",
        "summary_one_line": "intent_gate.py comment no secret vs preflight",
        "agent_task": "Goal: reduce misreading of risk gate semantics. In execution/intent_gate.py, add a short comment or docstring explaining the branch where risk_signing_secret is unset (gate behavior) versus what preflight warns in live mode. Acceptance: code review clarity only; no behavior change required unless bug found. Traceability: audit CODE-A1.",
        "affected_files": "execution/intent_gate.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "CODE-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "8",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-CI",
        "id": "FB-AUD-008",
        "kind": "platform",
        "status": "Open",
        "summary_one_line": "CI validate QUEUE_STACK vs open backlog",
        "agent_task": "Goal: prevent drift between QUEUE_STACK.csv and documented Open queue IDs. Add an optional script (e.g. scripts/ci_queue_consistency.sh) that fails or warns when Open IDs in CSV do not match QUEUE_ARCHIVE.MD / policy. Wire into CI as informational or blocking per team preference. Acceptance: documented in README or AGENTS.md. Traceability: audit CI-A1.",
        "affected_files": "scripts/|docs/QUEUE_STACK.csv|docs/QUEUE_ARCHIVE.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "CI-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "9",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-009",
        "kind": "hardening",
        "status": "Open",
        "summary_one_line": "CORS env allow_origins production allowlist",
        "agent_task": "Goal: safer production CORS. Make FastAPI CORSMiddleware allow_origins configurable via environment (e.g. comma-separated list). Default may remain permissive for dev but document that production must set explicit origins. Acceptance: README/RUNBOOKS updated; .env.example keys. Traceability: audit SEC-A1.",
        "affected_files": "control_plane/api.py|.env.example|README.md",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "SEC-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "10",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-010",
        "kind": "change",
        "status": "Open",
        "summary_one_line": "Document NM_AUTH_SESSION_COOKIE_SECURE HTTPS vs HTTP",
        "agent_task": "Goal: operators configure session cookies correctly. Document NM_AUTH_SESSION_COOKIE_SECURE and related cookie settings for HTTPS deployments vs local HTTP. Acceptance: README + RUNBOOKS + .env.example aligned. Traceability: audit SEC-A2.",
        "affected_files": "README.md|docs/RUNBOOKS.MD|.env.example",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "SEC-A2",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "11",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-011",
        "kind": "platform",
        "status": "Open",
        "summary_one_line": "pip-audit in docs or CI",
        "agent_task": "Goal: supply chain visibility. Add pip-audit (or equivalent) to developer docs and/or an optional CI job; policy for failing on HIGH/CRITICAL vs informational exit. Acceptance: documented command; pyproject optional extras unchanged unless needed. Traceability: audit SEC-A3.",
        "affected_files": "README.md|.github/workflows/ci.yml|pyproject.toml",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "SEC-A3",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "12",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-012",
        "kind": "hardening",
        "status": "Open",
        "summary_one_line": "Inventory httpx timeouts TLS",
        "agent_task": "Goal: outbound HTTP client hygiene. Inventory httpx usage in execution/, control_plane/, orchestration/ — document timeouts, TLS verify behavior, and error handling; fix critical gaps. Acceptance: short internal note in RUNBOOKS or table in AUDIT follow-up; tests if behavior changes. Traceability: audit SEC-A4.",
        "affected_files": "execution/|control_plane/|orchestration/",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|docs/RUNBOOKS.MD",
        "audit_id": "SEC-A4",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "13",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-TEST",
        "id": "FB-AUD-013",
        "kind": "platform",
        "status": "Open",
        "summary_one_line": "Tests require_mutate_operator wrong key",
        "agent_task": "Goal: lock API key enforcement. Add tests that require_mutate_operator rejects wrong or missing key when NM_CONTROL_PLANE_API_KEY is set. Acceptance: pytest passes; covers at least happy reject and missing header. Traceability: audit TEST-A1.",
        "affected_files": "tests/|control_plane/api.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "TEST-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "14",
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-DEBT",
        "id": "FB-AUD-014",
        "kind": "tech_debt",
        "status": "Open",
        "summary_one_line": "Inventory silent except pass",
        "agent_task": "Goal: reduce silent failure patterns. Incrementally inventory bare except / pass after exceptions; replace with logging where safe. Acceptance: phased PRs OK; do not destabilize hot paths; document scope in PR. Traceability: audit DEBT-A1.",
        "affected_files": "repo-wide (incremental)",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "DEBT-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "15",
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-DATA",
        "id": "FB-AUD-015",
        "kind": "reliability",
        "status": "Open",
        "summary_one_line": "QuestDB writer errors observability",
        "agent_task": "Goal: operators see persistence failures. Surface QuestDB writer / ingest errors via metrics or structured logs (counters or log lines with symbol/table context). Acceptance: documented in RUNBOOKS or observability doc; no PII in logs. Traceability: audit DATA-A1.",
        "affected_files": "data_plane/storage/|observability/",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|docs/Specs/OBSERVABILITY_AND_INFRA.MD",
        "audit_id": "DATA-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "16",
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-MT",
        "id": "FB-AUD-016",
        "kind": "hardening",
        "status": "Open",
        "summary_one_line": "Multi-tenant path review NM_MULTI_TENANT_DATA_SCOPING",
        "agent_task": "Goal: tenant isolation. Review paths when NM_MULTI_TENANT_DATA_SCOPING=true — data files, registry, and execution contexts must respect tenant prefix per AGENTS.md intent. Acceptance: gaps fixed or documented; add tests if behavior changes. Traceability: audit MT-A1.",
        "affected_files": "app/runtime/|execution/",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|AGENTS.md",
        "audit_id": "MT-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "17",
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-LEG",
        "id": "FB-AUD-017",
        "kind": "tech_debt",
        "status": "Open",
        "summary_one_line": "legacy/ isolation no V3 imports",
        "agent_task": "Goal: keep legacy snapshot isolated. No new imports from legacy/ into main V3 code paths; align with AGENTS.md and scripts/ci_spec_compliance.sh. Optionally strengthen CI grep. Acceptance: CI or script catches regressions. Traceability: audit LEGACY-A1.",
        "affected_files": "scripts/ci_spec_compliance.sh|legacy/",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|AGENTS.md",
        "audit_id": "LEGACY-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
]


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    path = root / "docs" / "QUEUE_STACK.csv"
    fieldnames = [
        "stack_order",
        "priority",
        "phase",
        "batch",
        "id",
        "kind",
        "status",
        "summary_one_line",
        "agent_task",
        "affected_files",
        "docs_refs",
        "audit_id",
        "anchor",
    ]
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
        w.writeheader()
        for row in ROWS:
            w.writerow(row)
    print(f"Wrote {len(ROWS)} rows to {path}")


if __name__ == "__main__":
    main()
