#!/usr/bin/env python3
"""Regenerate docs/QUEUE_STACK.csv (part of the queue system — see docs/QUEUE_SCHEMA.md).

Run from repo root: python scripts/generate_queue_stack.py
"""
from __future__ import annotations

import csv
from pathlib import Path

ROWS: list[dict[str, str]] = [
    {
        "stack_order": "1",
        "priority": "HIGH",
        "phase": "B",
        "batch": "SETUP-WIN",
        "id": "FB-SETUP-021",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "setup.bat: Docker Desktop install/wait/sign-in then compose",
        "agent_task": "COMPLETED. setup.bat: winget Docker.DockerDesktop or browser download if no docker CLI; loop docker info + start Docker Desktop.exe; pause for optional Hub sign-in; pull+up. NM_SKIP_DOCKER=1 skips Docker only.",
        "affected_files": "setup.bat",
        "docs_refs": "README.md|docs/READY_TO_RUN.MD|docs/WINDOWS_OPERATOR_UI.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "stack_order": "2",
        "priority": "HIGH",
        "phase": "B",
        "batch": "SETUP-LIN",
        "id": "FB-SETUP-022",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Linux/macOS setup.sh + run.sh (parity with setup.bat/run.bat)",
        "agent_task": "COMPLETED. setup.sh: venv, pip install -e .[dev,dashboard], docker compose pull+up or wait for engine / skip prompt; NM_SKIP_DOCKER=1. run.sh: uvicorn + power_supervisor + streamlit foreground.",
        "affected_files": "setup.sh|run.sh",
        "docs_refs": "README.md|docs/READY_TO_RUN.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "stack_order": "3",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "SETUP-DOC",
        "id": "FB-SETUP-023",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Docs: Windows Docker flow + Linux setup.sh/run.sh",
        "agent_task": "COMPLETED. README, READY_TO_RUN, WINDOWS_OPERATOR_UI, RUNBOOKS note NM_SKIP_DOCKER; chmod +x setup.sh run.sh.",
        "affected_files": "README.md|docs/READY_TO_RUN.MD|docs/WINDOWS_OPERATOR_UI.MD|docs/RUNBOOKS.MD|docs/QUEUE.MD|docs/QUEUE_ARCHIVE.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "stack_order": "4",
        "priority": "HIGH",
        "phase": "B",
        "batch": "RUN-DEV",
        "id": "FB-RUN-018",
        "kind": "fix",
        "status": "Done",
        "summary_one_line": "Qdrant memory: query_points for qdrant-client 1.17+",
        "agent_task": "COMPLETED. data_plane/memory/qdrant_memory.py uses QdrantClient.query_points instead of removed .search(); fixes AttributeError on Windows run.bat.",
        "affected_files": "data_plane/memory/qdrant_memory.py",
        "docs_refs": "docs/RUNBOOKS.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "stack_order": "5",
        "priority": "HIGH",
        "phase": "B",
        "batch": "RUN-DEV",
        "id": "FB-RUN-019",
        "kind": "fix",
        "status": "Done",
        "summary_one_line": "Default paper mode + skip orders when venue env creds missing",
        "agent_task": "COMPLETED. default.yaml execution.mode paper; execution/credentials.py + live_service skip submit_order when env creds absent (one startup WARNING). Stops live loop Coinbase error spam without NM_COINBASE_*.",
        "affected_files": "app/config/default.yaml|app/runtime/live_service.py|execution/credentials.py",
        "docs_refs": "README.md|docs/RUNBOOKS.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "stack_order": "6",
        "priority": "MEDIUM",
        "phase": "C",
        "batch": "INF-QDR",
        "id": "FB-INF-020",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Docker Qdrant image v1.17.1 (align with qdrant-client)",
        "agent_task": "COMPLETED. infra/docker-compose.yml uses qdrant/qdrant:v1.17.1 to match pip qdrant-client major/minor and reduce version skew warnings.",
        "affected_files": "infra/docker-compose.yml",
        "docs_refs": "docs/RUNBOOKS.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "stack_order": "7",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "UX-DOC",
        "id": "FB-UX-016",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Document Streamlit venue key onboarding (README + RUNBOOKS)",
        "agent_task": "COMPLETED. README § Control plane security: FB-UX-015/016 sign-up, NM_STREAMLIT_VENUE_KEYS_REQUIRED, pages 98/99, PER_ASSET_OPERATOR + RUNBOOKS link. RUNBOOKS: new § Streamlit venue key onboarding (FB-UX-015) — prerequisites, behavior, Kraken note.",
        "affected_files": "README.md|docs/RUNBOOKS.MD",
        "docs_refs": "docs/PER_ASSET_OPERATOR.MD|.env.example",
        "audit_id": "",
        "anchor": "#fb-ux-016-venue-onboarding-docs",
    },
    {
        "stack_order": "8",
        "priority": "HIGH",
        "phase": "B",
        "batch": "UX-ONB",
        "id": "FB-UX-015",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Sign up page + mandatory venue API key onboarding (Streamlit)",
        "agent_task": "COMPLETED. pages/99_Sign_up.py + pages/98_Setup_API_keys.py; /auth/me|login|register return venue_keys_*; NM_STREAMLIT_VENUE_KEYS_REQUIRED gates require_streamlit_app_access; 0_Login links to Sign up; sidebar Sign up link. Kraken remains env-only.",
        "affected_files": "control_plane/streamlit_util.py|control_plane/pages/0_Login.py|control_plane/pages/98_Setup_API_keys.py|control_plane/pages/99_Sign_up.py|control_plane/api.py|app/contracts/auth_login.py|app/runtime/auth_venue_status.py",
        "docs_refs": "docs/PER_ASSET_OPERATOR.MD|.env.example",
        "audit_id": "",
        "anchor": "#fb-ux-015-venue-onboarding",
    },
    {
        "stack_order": "9",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-DOC",
        "id": "FB-AUD-001",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Production API hardening (docs): TLS firewall API key CORS",
        "agent_task": "COMPLETED. Delivered: README and RUNBOOKS subsections for production control plane — TLS, firewall, NM_CONTROL_PLANE_API_KEY or session auth, and restricting CORS when API is not localhost-only. Traceability: audit DOC-A1.",
        "affected_files": "README.md|docs/RUNBOOKS.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "DOC-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "10",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-DOC",
        "id": "FB-AUD-002",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Streamlit route guard docs",
        "agent_task": "COMPLETED. Delivered: README + RUNBOOKS + streamlit_util docstrings for when to set NM_STREAMLIT_ROUTE_GUARD_ENABLED, session env alignment, and NM_CONTROL_PLANE_API_KEY bypass for automation. Traceability: audit DOC-A2.",
        "affected_files": "README.md|docs/RUNBOOKS.MD|control_plane/streamlit_util.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "DOC-A2",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "11",
        "priority": "MEDIUM",
        "phase": "C",
        "batch": "CONT-CI",
        "id": "FB-CONT-009",
        "kind": "fix",
        "status": "Done",
        "summary_one_line": "Fix CI: aquasecurity/trivy-action tag resolution",
        "agent_task": "COMPLETED. Pin aquasecurity/trivy-action to v0.35.0 in .github/workflows/ci.yml (upstream tag migration / supply-chain remediation). Traceability: docs/CI_ROOT_CAUSE_ANALYSIS_PROMPT.md.",
        "affected_files": ".github/workflows/ci.yml",
        "docs_refs": "docs/CI_ROOT_CAUSE_ANALYSIS_PROMPT.md",
        "audit_id": "",
        "anchor": "",
    },
    {
        "stack_order": "12",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-OPS",
        "id": "FB-AUD-003",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Startup warning when API key unset and bind non-loopback",
        "agent_task": "COMPLETED. WARNING in control_plane/api.py lifespan when NM_CONTROL_PLANE_API_KEY unset, session auth off, bind not loopback; RUNBOOKS cross-link. Traceability: OPS-A1.",
        "affected_files": "control_plane/api.py|docs/RUNBOOKS.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|docs/RUNBOOKS.MD",
        "audit_id": "OPS-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "13",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-OPS",
        "id": "FB-AUD-004",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Optional rate limiting for control_plane public exposure",
        "agent_task": "COMPLETED. ControlPlaneRateLimitMiddleware + NM_CONTROL_PLANE_RATE_LIMIT_ENABLED / PER_MINUTE; RUNBOOKS. Traceability: OPS-A2.",
        "affected_files": "control_plane/api.py|docs/RUNBOOKS.MD|infra/",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "OPS-A2",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "14",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-QA",
        "id": "FB-AUD-005",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Exception logging pass live_service.py",
        "agent_task": "COMPLETED. Broad handlers in live_service log symbols (position_reconcile, sentiment). Traceability: QA-A1.",
        "affected_files": "app/runtime/live_service.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "QA-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "15",
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-QA",
        "id": "FB-AUD-006",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Exception logging pass asset_page streamlit_util",
        "agent_task": "COMPLETED. asset_page API base caption on failure; streamlit_util operator_logout logs httpx errors. Traceability: QA-A2.",
        "affected_files": "control_plane/asset_page.py|control_plane/streamlit_util.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "QA-A2",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "16",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-CODE",
        "id": "FB-AUD-007",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "intent_gate.py comment no secret vs preflight",
        "agent_task": "COMPLETED. Docstring in execution/intent_gate.py for unsigned vs preflight. Traceability: CODE-A1.",
        "affected_files": "execution/intent_gate.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "CODE-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "17",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-CI",
        "id": "FB-AUD-008",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "CI validate QUEUE_STACK vs open backlog",
        "agent_task": "COMPLETED. scripts/ci_queue_consistency.sh; lint-test job in .github/workflows/ci.yml. Traceability: CI-A1.",
        "affected_files": "scripts/ci_queue_consistency.sh|docs/QUEUE_STACK.csv|docs/QUEUE_ARCHIVE.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "CI-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "18",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-009",
        "kind": "hardening",
        "status": "Done",
        "summary_one_line": "CORS env allow_origins production allowlist",
        "agent_task": "COMPLETED. NM_CONTROL_PLANE_CORS_ALLOW_ORIGINS + README/RUNBOOKS/.env.example. Traceability: SEC-A1.",
        "affected_files": "control_plane/api.py|.env.example|README.md",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "SEC-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "19",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-010",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Document NM_AUTH_SESSION_COOKIE_SECURE HTTPS vs HTTP",
        "agent_task": "COMPLETED. README + RUNBOOKS + .env.example session cookie HTTPS guidance. Traceability: SEC-A2.",
        "affected_files": "README.md|docs/RUNBOOKS.MD|.env.example",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "SEC-A2",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "20",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-011",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "pip-audit in docs or CI",
        "agent_task": "COMPLETED. CI job pip-audit (continue-on-error); README command. Traceability: SEC-A3.",
        "affected_files": "README.md|.github/workflows/ci.yml",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "SEC-A3",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "21",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-012",
        "kind": "hardening",
        "status": "Done",
        "summary_one_line": "Inventory httpx timeouts TLS",
        "agent_task": "COMPLETED. RUNBOOKS § Outbound HTTP (httpx) — timeouts and TLS defaults. Traceability: SEC-A4.",
        "affected_files": "execution/|control_plane/|orchestration/",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|docs/RUNBOOKS.MD",
        "audit_id": "SEC-A4",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "22",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-TEST",
        "id": "FB-AUD-013",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Tests require_mutate_operator wrong key",
        "agent_task": "COMPLETED. tests/test_control_plane_api_key_mutate.py. Traceability: TEST-A1.",
        "affected_files": "tests/test_control_plane_api_key_mutate.py|control_plane/api.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "TEST-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "23",
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-DEBT",
        "id": "FB-AUD-014",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Inventory silent except pass",
        "agent_task": "COMPLETED. RUNBOOKS inventory note (grep for bare except); incremental hardening deferred. Traceability: DEBT-A1.",
        "affected_files": "docs/RUNBOOKS.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "DEBT-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "24",
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-DATA",
        "id": "FB-AUD-015",
        "kind": "reliability",
        "status": "Done",
        "summary_one_line": "QuestDB writer errors observability",
        "agent_task": "COMPLETED. Prometheus tb_questdb_write_fail_total + RUNBOOKS. Traceability: DATA-A1.",
        "affected_files": "data_plane/storage/questdb.py|observability/metrics.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|docs/Specs/OBSERVABILITY_AND_INFRA.MD",
        "audit_id": "DATA-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "25",
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-MT",
        "id": "FB-AUD-016",
        "kind": "hardening",
        "status": "Done",
        "summary_one_line": "Multi-tenant path review NM_MULTI_TENANT_DATA_SCOPING",
        "agent_task": "COMPLETED. RUNBOOKS § Multi-tenant data scoping — review checklist; aligns with tenant_ctx + AGENTS.md. Traceability: MT-A1.",
        "affected_files": "docs/RUNBOOKS.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|AGENTS.md",
        "audit_id": "MT-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "26",
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-LEG",
        "id": "FB-AUD-017",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "legacy/ isolation no V3 imports",
        "agent_task": "COMPLETED. scripts/ci_spec_compliance.sh greps legacy package imports outside legacy/. Traceability: LEGACY-A1.",
        "affected_files": "scripts/ci_spec_compliance.sh|legacy/",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|AGENTS.md",
        "audit_id": "LEGACY-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "stack_order": "27",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SUP",
        "id": "FB-AUD-018",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "pip-audit CI: dedicated venv + release-blocking",
        "agent_task": "COMPLETED. scripts/ci_pip_audit.sh builds .audit-venv, pip install -e .[dev], pip-audit -l; CI step blocks merges. requests>=2.33.0. Traceability: AUD-SUP-001.",
        "affected_files": "scripts/ci_pip_audit.sh|.github/workflows/ci.yml|pyproject.toml|README.md|docs/RUNBOOKS.MD",
        "docs_refs": "docs/reports/AUDIT_REPORT_2026-04-13_full.md",
        "audit_id": "AUD-SUP-001",
        "anchor": "#full-audit-2026-04-13",
    },
    {
        "stack_order": "28",
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-019",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Gitleaks secret scan in CI (Docker)",
        "agent_task": "COMPLETED. CI job gitleaks runs zricethezav/gitleaks Docker image on full checkout; AGENTS.md + RUNBOOKS local docker one-liner. Traceability: AUD-SEC-REPO-001.",
        "affected_files": ".github/workflows/ci.yml|AGENTS.md|docs/RUNBOOKS.MD",
        "docs_refs": "docs/reports/AUDIT_REPORT_2026-04-13_full.md",
        "audit_id": "AUD-SEC-REPO-001",
        "anchor": "#full-audit-2026-04-13",
    },
    {
        "stack_order": "29",
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-STATIC",
        "id": "FB-AUD-020",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Bandit High severity in CI + pyproject",
        "agent_task": "COMPLETED. scripts/ci_bandit.sh, [tool.bandit] in pyproject.toml, dev extra bandit[toml]; nosec on reviewed RSS/torch lines. Traceability: AUD-STATIC-001.",
        "affected_files": "scripts/ci_bandit.sh|pyproject.toml|.github/workflows/ci.yml|data_plane/ingest/rss_news.py|forecaster_model/inference/torch_infer.py",
        "docs_refs": "docs/reports/AUDIT_REPORT_2026-04-13_full.md",
        "audit_id": "AUD-STATIC-001",
        "anchor": "#full-audit-2026-04-13",
    },
    {
        "stack_order": "9999",
        "priority": "LOW",
        "phase": "D",
        "batch": "",
        "id": "_QUEUE_EMPTY_",
        "kind": "deferred",
        "status": "empty",
        "summary_one_line": "No open queue items",
        "agent_task": "N/A — add work via QUEUE.MD §6.",
        "affected_files": "",
        "docs_refs": "",
        "audit_id": "",
        "anchor": "",
    },

]


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    path = root / "docs" / "QUEUE_STACK.csv"
    fieldnames = [
        "stack_order",
        "priority",
        "phase",
        "batch",
        "id",
        "kind",
        "status",
        "summary_one_line",
        "agent_task",
        "affected_files",
        "docs_refs",
        "audit_id",
        "anchor",
    ]
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
        w.writeheader()
        for row in ROWS:
            w.writerow(row)
    print(f"Wrote {len(ROWS)} rows to {path}")


if __name__ == "__main__":
    main()
