#!/usr/bin/env python3
"""Regenerate docs/QUEUE_STACK.csv (part of the queue system — see docs/QUEUE_SCHEMA.md).

Run from repo root: python scripts/generate_queue_stack.py

**stack_order:** Do not put ``stack_order`` in each ``ROWS`` dict. Order in ``ROWS`` is the
pull order (top = next); the script assigns ``stack_order`` as 1..N for real rows and
``9999`` for the ``_QUEUE_EMPTY_`` sentinel. Reorder or append dicts only — no renumbering.
"""
from __future__ import annotations

import csv
from pathlib import Path

ROWS: list[dict[str, str]] = [
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "DOC-UX",
        "id": "FB-DOC-025",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "README: friendly rewrite + copy-paste clone/setup/run",
        "agent_task": "COMPLETED. README: plain-English intro, architecture snippet, Windows/Linux quick setup, copy-paste blocks; lighter technical jargon.",
        "affected_files": "README.md",
        "docs_refs": "docs/READY_TO_RUN.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "DOC-UX",
        "id": "FB-DOC-024",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "README: Quick start section first (setup.bat / setup.sh table)",
        "agent_task": "COMPLETED. README: move Quick start to top after title; table setup+run; manual setup in details; trim duplicate Windows/Linux sections.",
        "affected_files": "README.md",
        "docs_refs": "docs/READY_TO_RUN.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "priority": "HIGH",
        "phase": "B",
        "batch": "SETUP-WIN",
        "id": "FB-SETUP-021",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "setup.bat: Docker Desktop install/wait/sign-in then compose",
        "agent_task": "COMPLETED. setup.bat: winget Docker.DockerDesktop or browser download if no docker CLI; loop docker info + start Docker Desktop.exe; pause for optional Hub sign-in; pull+up. NM_SKIP_DOCKER=1 skips Docker only.",
        "affected_files": "setup.bat",
        "docs_refs": "README.md|docs/READY_TO_RUN.MD|docs/WINDOWS_OPERATOR_UI.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "priority": "HIGH",
        "phase": "B",
        "batch": "SETUP-LIN",
        "id": "FB-SETUP-022",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Linux/macOS setup.sh + run.sh (parity with setup.bat/run.bat)",
        "agent_task": "COMPLETED. setup.sh: venv, pip install -e .[dev,dashboard], docker compose pull+up or wait for engine / skip prompt; NM_SKIP_DOCKER=1. run.sh: uvicorn + power_supervisor + streamlit foreground.",
        "affected_files": "setup.sh|run.sh",
        "docs_refs": "README.md|docs/READY_TO_RUN.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "SETUP-DOC",
        "id": "FB-SETUP-023",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Docs: Windows Docker flow + Linux setup.sh/run.sh",
        "agent_task": "COMPLETED. README, READY_TO_RUN, WINDOWS_OPERATOR_UI, RUNBOOKS note NM_SKIP_DOCKER; chmod +x setup.sh run.sh.",
        "affected_files": "README.md|docs/READY_TO_RUN.MD|docs/WINDOWS_OPERATOR_UI.MD|docs/RUNBOOKS.MD|docs/QUEUE.MD|docs/QUEUE_ARCHIVE.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "priority": "HIGH",
        "phase": "B",
        "batch": "RUN-DEV",
        "id": "FB-RUN-018",
        "kind": "fix",
        "status": "Done",
        "summary_one_line": "Qdrant memory: query_points for qdrant-client 1.17+",
        "agent_task": "COMPLETED. data_plane/memory/qdrant_memory.py uses QdrantClient.query_points instead of removed .search(); fixes AttributeError on Windows run.bat.",
        "affected_files": "data_plane/memory/qdrant_memory.py",
        "docs_refs": "docs/RUNBOOKS.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "priority": "HIGH",
        "phase": "B",
        "batch": "RUN-DEV",
        "id": "FB-RUN-019",
        "kind": "fix",
        "status": "Done",
        "summary_one_line": "Default paper mode + skip orders when venue env creds missing",
        "agent_task": "COMPLETED. default.yaml execution.mode paper; execution/credentials.py + live_service skip submit_order when env creds absent (one startup WARNING). Stops live loop Coinbase error spam without NM_COINBASE_*.",
        "affected_files": "app/config/default.yaml|app/runtime/live_service.py|execution/credentials.py",
        "docs_refs": "README.md|docs/RUNBOOKS.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "priority": "MEDIUM",
        "phase": "C",
        "batch": "INF-QDR",
        "id": "FB-INF-020",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Docker Qdrant image v1.17.1 (align with qdrant-client)",
        "agent_task": "COMPLETED. infra/docker-compose.yml uses qdrant/qdrant:v1.17.1 to match pip qdrant-client major/minor and reduce version skew warnings.",
        "affected_files": "infra/docker-compose.yml",
        "docs_refs": "docs/RUNBOOKS.MD",
        "audit_id": "",
        "anchor": "",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "UX-DOC",
        "id": "FB-UX-016",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Document Streamlit venue key onboarding (README + RUNBOOKS)",
        "agent_task": "COMPLETED. README § Control plane security: FB-UX-015/016 sign-up, NM_STREAMLIT_VENUE_KEYS_REQUIRED, pages 98/99, PER_ASSET_OPERATOR + RUNBOOKS link. RUNBOOKS: new § Streamlit venue key onboarding (FB-UX-015) — prerequisites, behavior, Kraken note.",
        "affected_files": "README.md|docs/RUNBOOKS.MD",
        "docs_refs": "docs/PER_ASSET_OPERATOR.MD|.env.example",
        "audit_id": "",
        "anchor": "#fb-ux-016-venue-onboarding-docs",
    },
    {
        "priority": "HIGH",
        "phase": "B",
        "batch": "UX-ONB",
        "id": "FB-UX-015",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Sign up page + mandatory venue API key onboarding (Streamlit)",
        "agent_task": "COMPLETED. pages/99_Sign_up.py + pages/98_Setup_API_keys.py; /auth/me|login|register return venue_keys_*; NM_STREAMLIT_VENUE_KEYS_REQUIRED gates require_streamlit_app_access; 0_Login links to Sign up; sidebar Sign up link. Kraken remains env-only.",
        "affected_files": "control_plane/streamlit_util.py|control_plane/pages/0_Login.py|control_plane/pages/98_Setup_API_keys.py|control_plane/pages/99_Sign_up.py|control_plane/api.py|app/contracts/auth_login.py|app/runtime/auth_venue_status.py",
        "docs_refs": "docs/PER_ASSET_OPERATOR.MD|.env.example",
        "audit_id": "",
        "anchor": "#fb-ux-015-venue-onboarding",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-DOC",
        "id": "FB-AUD-001",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Production API hardening (docs): TLS firewall API key CORS",
        "agent_task": "COMPLETED. Delivered: README and RUNBOOKS subsections for production control plane — TLS, firewall, NM_CONTROL_PLANE_API_KEY or session auth, and restricting CORS when API is not localhost-only. Traceability: audit DOC-A1.",
        "affected_files": "README.md|docs/RUNBOOKS.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "DOC-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-DOC",
        "id": "FB-AUD-002",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Streamlit route guard docs",
        "agent_task": "COMPLETED. Delivered: README + RUNBOOKS + streamlit_util docstrings for when to set NM_STREAMLIT_ROUTE_GUARD_ENABLED, session env alignment, and NM_CONTROL_PLANE_API_KEY bypass for automation. Traceability: audit DOC-A2.",
        "affected_files": "README.md|docs/RUNBOOKS.MD|control_plane/streamlit_util.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "DOC-A2",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "MEDIUM",
        "phase": "C",
        "batch": "CONT-CI",
        "id": "FB-CONT-009",
        "kind": "fix",
        "status": "Done",
        "summary_one_line": "Fix CI: aquasecurity/trivy-action tag resolution",
        "agent_task": "COMPLETED. Pin aquasecurity/trivy-action to v0.35.0 in .github/workflows/ci.yml (upstream tag migration / supply-chain remediation). Traceability: docs/CI_ROOT_CAUSE_ANALYSIS_PROMPT.md.",
        "affected_files": ".github/workflows/ci.yml",
        "docs_refs": "docs/CI_ROOT_CAUSE_ANALYSIS_PROMPT.md",
        "audit_id": "",
        "anchor": "",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-OPS",
        "id": "FB-AUD-003",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Startup warning when API key unset and bind non-loopback",
        "agent_task": "COMPLETED. WARNING in control_plane/api.py lifespan when NM_CONTROL_PLANE_API_KEY unset, session auth off, bind not loopback; RUNBOOKS cross-link. Traceability: OPS-A1.",
        "affected_files": "control_plane/api.py|docs/RUNBOOKS.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|docs/RUNBOOKS.MD",
        "audit_id": "OPS-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-OPS",
        "id": "FB-AUD-004",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Optional rate limiting for control_plane public exposure",
        "agent_task": "COMPLETED. ControlPlaneRateLimitMiddleware + NM_CONTROL_PLANE_RATE_LIMIT_ENABLED / PER_MINUTE; RUNBOOKS. Traceability: OPS-A2.",
        "affected_files": "control_plane/api.py|docs/RUNBOOKS.MD|infra/",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "OPS-A2",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-QA",
        "id": "FB-AUD-005",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Exception logging pass live_service.py",
        "agent_task": "COMPLETED. Broad handlers in live_service log symbols (position_reconcile, sentiment). Traceability: QA-A1.",
        "affected_files": "app/runtime/live_service.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "QA-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-QA",
        "id": "FB-AUD-006",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Exception logging pass asset_page streamlit_util",
        "agent_task": "COMPLETED. asset_page API base caption on failure; streamlit_util operator_logout logs httpx errors. Traceability: QA-A2.",
        "affected_files": "control_plane/asset_page.py|control_plane/streamlit_util.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "QA-A2",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-CODE",
        "id": "FB-AUD-007",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "intent_gate.py comment no secret vs preflight",
        "agent_task": "COMPLETED. Docstring in execution/intent_gate.py for unsigned vs preflight. Traceability: CODE-A1.",
        "affected_files": "execution/intent_gate.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "CODE-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-CI",
        "id": "FB-AUD-008",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "CI validate QUEUE_STACK vs open backlog",
        "agent_task": "COMPLETED. scripts/ci_queue_consistency.py; lint-test job in .github/workflows/ci.yml. Traceability: CI-A1.",
        "affected_files": "scripts/ci_queue_consistency.py|docs/QUEUE_STACK.csv|docs/QUEUE_ARCHIVE.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "CI-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-009",
        "kind": "hardening",
        "status": "Done",
        "summary_one_line": "CORS env allow_origins production allowlist",
        "agent_task": "COMPLETED. NM_CONTROL_PLANE_CORS_ALLOW_ORIGINS + README/RUNBOOKS/.env.example. Traceability: SEC-A1.",
        "affected_files": "control_plane/api.py|.env.example|README.md",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "SEC-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-010",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Document NM_AUTH_SESSION_COOKIE_SECURE HTTPS vs HTTP",
        "agent_task": "COMPLETED. README + RUNBOOKS + .env.example session cookie HTTPS guidance. Traceability: SEC-A2.",
        "affected_files": "README.md|docs/RUNBOOKS.MD|.env.example",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "SEC-A2",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-011",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "pip-audit in docs or CI",
        "agent_task": "COMPLETED. CI job pip-audit (continue-on-error); README command. Traceability: SEC-A3.",
        "affected_files": "README.md|.github/workflows/ci.yml",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "SEC-A3",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-012",
        "kind": "hardening",
        "status": "Done",
        "summary_one_line": "Inventory httpx timeouts TLS",
        "agent_task": "COMPLETED. RUNBOOKS § Outbound HTTP (httpx) — timeouts and TLS defaults. Traceability: SEC-A4.",
        "affected_files": "execution/|control_plane/|orchestration/",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|docs/RUNBOOKS.MD",
        "audit_id": "SEC-A4",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-TEST",
        "id": "FB-AUD-013",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Tests require_mutate_operator wrong key",
        "agent_task": "COMPLETED. tests/test_control_plane_api_key_mutate.py. Traceability: TEST-A1.",
        "affected_files": "tests/test_control_plane_api_key_mutate.py|control_plane/api.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "TEST-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-DEBT",
        "id": "FB-AUD-014",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Inventory silent except pass",
        "agent_task": "COMPLETED. RUNBOOKS inventory note (grep for bare except); incremental hardening deferred. Traceability: DEBT-A1.",
        "affected_files": "docs/RUNBOOKS.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD",
        "audit_id": "DEBT-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-DATA",
        "id": "FB-AUD-015",
        "kind": "reliability",
        "status": "Done",
        "summary_one_line": "QuestDB writer errors observability",
        "agent_task": "COMPLETED. Prometheus tb_questdb_write_fail_total + RUNBOOKS. Traceability: DATA-A1.",
        "affected_files": "data_plane/storage/questdb.py|observability/metrics.py",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|docs/Specs/OBSERVABILITY_AND_INFRA.MD",
        "audit_id": "DATA-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-MT",
        "id": "FB-AUD-016",
        "kind": "hardening",
        "status": "Done",
        "summary_one_line": "Multi-tenant path review NM_MULTI_TENANT_DATA_SCOPING",
        "agent_task": "COMPLETED. RUNBOOKS § Multi-tenant data scoping — review checklist; aligns with tenant_ctx + AGENTS.md. Traceability: MT-A1.",
        "affected_files": "docs/RUNBOOKS.MD",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|AGENTS.md",
        "audit_id": "MT-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-LEG",
        "id": "FB-AUD-017",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "legacy/ isolation no V3 imports",
        "agent_task": "COMPLETED. scripts/ci_spec_compliance.sh greps legacy package imports outside legacy/. Traceability: LEGACY-A1.",
        "affected_files": "scripts/ci_spec_compliance.sh|legacy/",
        "docs_refs": "docs/AUDIT_CODE_REVIEW.MD|AGENTS.md",
        "audit_id": "LEGACY-A1",
        "anchor": "#25-post-audit-hardening-fb-aud",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SUP",
        "id": "FB-AUD-018",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "pip-audit CI: dedicated venv + release-blocking",
        "agent_task": "COMPLETED. scripts/ci_pip_audit.sh builds .audit-venv, pip install -e .[dev], pip-audit -l; CI step blocks merges. requests>=2.33.0. Traceability: AUD-SUP-001.",
        "affected_files": "scripts/ci_pip_audit.sh|.github/workflows/ci.yml|pyproject.toml|README.md|docs/RUNBOOKS.MD",
        "docs_refs": "docs/reports/AUDIT_REPORT_2026-04-13_full.md",
        "audit_id": "AUD-SUP-001",
        "anchor": "#full-audit-2026-04-13",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "AUD-SEC",
        "id": "FB-AUD-019",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Gitleaks secret scan in CI (Docker)",
        "agent_task": "COMPLETED. CI job gitleaks runs zricethezav/gitleaks Docker image on full checkout; AGENTS.md + RUNBOOKS local docker one-liner. Traceability: AUD-SEC-REPO-001.",
        "affected_files": ".github/workflows/ci.yml|AGENTS.md|docs/RUNBOOKS.MD",
        "docs_refs": "docs/reports/AUDIT_REPORT_2026-04-13_full.md",
        "audit_id": "AUD-SEC-REPO-001",
        "anchor": "#full-audit-2026-04-13",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "AUD-STATIC",
        "id": "FB-AUD-020",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Bandit High severity in CI + pyproject",
        "agent_task": "COMPLETED. scripts/ci_bandit.sh, [tool.bandit] in pyproject.toml, dev extra bandit[toml]; nosec on reviewed RSS/torch lines. Traceability: AUD-STATIC-001.",
        "affected_files": "scripts/ci_bandit.sh|pyproject.toml|.github/workflows/ci.yml|data_plane/ingest/rss_news.py|forecaster_model/inference/torch_infer.py",
        "docs_refs": "docs/reports/AUDIT_REPORT_2026-04-13_full.md",
        "audit_id": "AUD-STATIC-001",
        "anchor": "#full-audit-2026-04-13",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-AUD",
        "id": "FB-CAN-001",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Produce canonical gap audit artifact and domain inventory",
        "agent_task": "COMPLETED. docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md is the authoritative repo-vs-canonical audit (runtime entrypoints, architecture/config/docs/CI inventory, domain gaps vs canonical/*.md, delete/create/refactor targets, risks, ordered plan, explicit FB-CAN-001..014 domain table + extended ID list). Reviewed 2026-04-18.",
        "affected_files": "docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md|app/runtime/live_service.py|decision_engine/|risk_engine/|execution/|backtesting/|app/config/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md|docs/Specs/SYSTEM_OVERVIEW.MD|docs/QUEUE.MD",
        "audit_id": "CANONICAL-GAP-AUDIT",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-DOC",
        "id": "FB-CAN-002",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Adopt canonical specs and de-canonicalize conflicting in-repo specs",
        "agent_task": "COMPLETED. Added docs/CANONICAL_SPEC_INDEX.MD (precedence + canonical file index); README + docs/Specs/README.MD + docs/Human Provided Specs/README.MD declare new_specs/canonical as target architecture; blockquote banners on all docs/Specs/*.MD and legacy root Human Provided Specs (MASTER/FORECASTER/POLICY/NIGHTLY/INITIAL) pointing to index. Historical docs retained, marked as-built or legacy vs APEX canonical.",
        "affected_files": "README.md|docs/Specs/|docs/Human Provided Specs/|docs/QUEUE_ARCHIVE.MD",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md|docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md",
        "audit_id": "CANONICAL-DOCS",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-CFG",
        "id": "FB-CAN-003",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Overhaul configuration schema to canonical domains",
        "agent_task": "COMPLETED. Added app/config/canonical_config.py (CanonicalMetadata, CanonicalDomains, CanonicalRuntimeConfig), legacy projection synthesize_canonical_from_legacy + merge with optional default.yaml apex_canonical; AppSettings.canonical + load_settings binding; default.yaml apex_canonical stub; tests; docs APP_CONFIG_AND_CONTRACTS, CANONICAL_SPEC_INDEX, QUEUE_SCHEMA.",
        "affected_files": "app/config/settings.py|app/config/default.yaml|tests/|docs/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md",
        "audit_id": "CANONICAL-CONFIG",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-STATE",
        "id": "FB-CAN-004",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement canonical state/regime engine with degradation propagation",
        "agent_task": "COMPLETED. decision_engine/state_engine.py build_canonical_state + RiskState canonical_size_multiplier; app/contracts/canonical_state.py + RegimeOutput.apex; RiskEngine applies multiplier; tests. Legacy HMM semantic retained for compatibility; apex is source of truth for 5-class regime + degradation.",
        "affected_files": "decision_engine/|models/|app/contracts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_State_Regime_Logic_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md",
        "audit_id": "CANONICAL-STATE",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-TRIG",
        "id": "FB-CAN-005",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement canonical three-stage trigger engine",
        "agent_task": "COMPLETED. app/contracts/trigger.py TriggerOutput; decision_engine/trigger_engine.py evaluate_trigger; pipeline wires trigger; forecast_diagnostics['trigger'] for replay; run_spec_policy_step gates proposal + scales size by trigger_confidence; tests test_trigger_engine.",
        "affected_files": "decision_engine/|app/contracts/|backtesting/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Trigger_Math_Pseudocode_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Decision_Service_Feature_Schema_and_Data_Contracts_v1_0.md",
        "audit_id": "CANONICAL-TRIGGER",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-AUCT",
        "id": "FB-CAN-006",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement opportunity auction scoring and selection constraints",
        "agent_task": "COMPLETED. app/contracts/auction.py; decision_engine/auction_engine.py run_opportunity_auction (long/short/flat ranked, penalties, top-N=1, notional cap); spec_policy_step integrates; forecast_diagnostics['auction']; tests test_auction_engine.",
        "affected_files": "decision_engine/|app/contracts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Auction_Scoring_Constraints_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md",
        "audit_id": "CANONICAL-AUCTION",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-RISK",
        "id": "FB-CAN-007",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Replace hard-gate risk engine with canonical risk/sizing architecture",
        "agent_task": "COMPLETED. risk_engine/canonical_sizing.py + RiskEngine uses compute_canonical_notional; RiskState sizing inputs from merge_canonical_into_risk; run_step passes portfolio_equity_usd; last_risk_sizing diagnostics; tests test_canonical_risk_sizing.",
        "affected_files": "risk_engine/engine.py|app/contracts/risk.py|app/contracts/decisions.py|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md|docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md",
        "audit_id": "CANONICAL-RISK",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-EXEC",
        "id": "FB-CAN-008",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Replace execution logic with confidence/style/stress/partial-fill model",
        "agent_task": "COMPLETED. execution/execution_logic.py + ExecutionGuidance; ExecutionService.prepare; live_service builds execution_context + feedback; to_order_intent(sign=False) path; tests test_execution_logic.",
        "affected_files": "execution/service.py|execution/|app/contracts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Execution_Logic_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md",
        "audit_id": "CANONICAL-EXEC",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-REPL",
        "id": "FB-CAN-009",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Align replay/simulation interface with canonical event contracts",
        "agent_task": "COMPLETED. app/contracts/replay_events.py; replay_contract + emit_canonical_events + fault_injection; replay_core + deterministic run_decision_tick; decision_output includes trigger/auction/risk sizing; tests test_replay_canonical_events.",
        "affected_files": "backtesting/|decision_engine/run_step.py|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Replay_and_Simulation_Interface_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Decision_Service_Feature_Schema_and_Data_Contracts_v1_0.md",
        "audit_id": "CANONICAL-REPLAY",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-MON",
        "id": "FB-CAN-010",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement canonical monitoring and alerting metric families",
        "agent_task": "COMPLETED. observability/canonical_metrics.py tb_canonical_*; record in run_decision_tick; docs MONITORING_CANONICAL.MD; Grafana tb-overview panels; tests test_canonical_metrics.",
        "affected_files": "observability/|control_plane/|infra/|docs/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-MONITORING",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-GOV",
        "id": "FB-CAN-011",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Add release gating and experiment registry integration",
        "agent_task": "Implement config/logic release lifecycle and promotion gates (research→simulation→shadow→live), with immutable versioning and rollback metadata. Add experiment registry records linking hypotheses, replay/scenario evidence, shadow results, and release candidates to enforce canonical governance requirements.",
        "affected_files": "models/|orchestration/|scripts/|docs/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Research_Experiment_Registry_Spec_v1_0.md",
        "audit_id": "CANONICAL-GOVERNANCE",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-DEL",
        "id": "FB-CAN-012",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Hard-delete obsolete legacy architecture paths post-migration",
        "agent_task": "After replacement modules are active, delete obsolete pipeline code and contracts tied to legacy architecture (ForecastPacket/PolicySystem-only flow, stale wrappers, conflicting settings, superseded docs) per the canonical gap audit deletion list. Do not keep long-term dual-path logic; only preserve temporary shims with explicit expiry and removal commits.",
        "affected_files": "decision_engine/|risk_engine/|execution/|app/config/|docs/Specs/|tests/",
        "docs_refs": "docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md",
        "audit_id": "CANONICAL-DELETION",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "B",
        "batch": "CAN-TEST",
        "id": "FB-CAN-013",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Replace tests and CI gates for canonical behavior",
        "agent_task": "Replace obsolete tests asserting legacy architecture, then add canonical contract tests for state/trigger/auction/risk/execution/replay/governance domains. Update CI scripts and workflow so merge gates enforce canonical schemas and release-gating evidence checks rather than legacy-only invariants.",
        "affected_files": "tests/|scripts/|.github/workflows/ci.yml|docs/Specs/TESTING_AND_CI.MD",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md|docs/Human Provided Specs/new_specs/canonical/APEX_Replay_and_Simulation_Interface_Spec_v1_0.md",
        "audit_id": "CANONICAL-TEST-CI",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-CLEAN",
        "id": "FB-CAN-014",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Final canonical docs and module-structure cleanup",
        "agent_task": "Finalize end-state repository structure and docs after canonical migration: publish module map, responsibility boundaries, removed-module tombstones, operator runbooks, and migration notes. Ensure README/docs/spec pointers consistently reference canonical architecture and no stale contradictory guidance remains.",
        "affected_files": "README.md|docs/|app/|decision_engine/|risk_engine/|execution/|backtesting/",
        "docs_refs": "docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md|docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md",
        "audit_id": "CANONICAL-CLEANUP",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-DATA",
        "id": "FB-CAN-015",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Canonical data contract layer for market/structural/safety/execution snapshots",
        "agent_task": "Implement canonical input contract models and validators for Market Snapshot, Structural Signal Snapshot, Safety/Regime Snapshot, Execution Feedback Snapshot, and Service Configuration Snapshot. Replace ad-hoc feature dictionaries at decision boundaries with typed canonical snapshots and explicit freshness/confidence semantics from the canonical data contract spec.",
        "affected_files": "app/contracts/|decision_engine/|data_plane/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Decision_Service_Feature_Schema_and_Data_Contracts_v1_0.md",
        "audit_id": "CANONICAL-DATA-CONTRACTS",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-NORM",
        "id": "FB-CAN-016",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Normalize ingestion outputs to canonical feature families and confidence fields",
        "agent_task": "Refactor ingest/normalization outputs so all upstream signals carry canonical freshness/reliability/confidence fields and normalized naming. Add mapping/validation for required signal families and reject incomplete snapshots according to canonical degradation rules.",
        "affected_files": "data_plane/ingest/|data_plane/features/|app/contracts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Decision_Service_Feature_Schema_and_Data_Contracts_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md",
        "audit_id": "CANONICAL-NORMALIZATION",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-STR",
        "id": "FB-CAN-017",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Replace legacy ForecastPacket-centric structure output contract",
        "agent_task": "Replace or adapt ForecastPacket-centric interfaces so structure/forecast outputs align to canonical structure inputs required by trigger and auction domains. Remove legacy-only packet fields that do not map to canonical semantics and add migration adapters with expiry if needed.",
        "affected_files": "app/contracts/forecast_packet.py|decision_engine/pipeline.py|forecaster_model/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md",
        "audit_id": "CANONICAL-STRUCTURE-CONTRACT",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-CARRY",
        "id": "FB-CAN-018",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement carry sleeve domain required by canonical architecture",
        "agent_task": "Create explicit carry sleeve module with eligibility, sizing boundaries, and interaction rules with directional strategy risk. Integrate carry sleeve observability and replay hooks so carry behavior is deterministic and auditable.",
        "affected_files": "carry_sleeve/|decision_engine/|risk_engine/|backtesting/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md|docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md",
        "audit_id": "CANONICAL-CARRY",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-DEL-DEC",
        "id": "FB-CAN-019",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Delete obsolete decision_engine modules after canonical cutover",
        "agent_task": "After state/trigger/auction orchestration is active, delete obsolete decision_engine modules that encode legacy DecisionPipeline/PolicySystem single-proposal flow. Update imports and remove dead code paths/tests tied to removed modules in the same PR slice.",
        "affected_files": "decision_engine/|tests/",
        "docs_refs": "docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md",
        "audit_id": "CANONICAL-DELETE-DECISION",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-DEL-RISK",
        "id": "FB-CAN-020",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Delete obsolete risk_engine branches and contracts",
        "agent_task": "Remove legacy hard-gate-only risk branches and contract fields that conflict with canonical risk/sizing architecture once canonical risk engine is the only active path. Ensure safety overrides and intent signing invariants remain enforced.",
        "affected_files": "risk_engine/|app/contracts/risk.py|app/contracts/decisions.py|tests/",
        "docs_refs": "docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md|docs/RISK_PRECEDENCE.MD",
        "audit_id": "CANONICAL-DELETE-RISK",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-DEL-EXEC",
        "id": "FB-CAN-021",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Delete obsolete thin execution-only paths",
        "agent_task": "Delete execution service code paths that assume submit-only behavior once canonical execution confidence/style/stress/partial-fill modules are active. Keep venue adapter interfaces but remove deprecated wrappers and dead routing branches.",
        "affected_files": "execution/service.py|execution/|tests/",
        "docs_refs": "docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md|docs/Human Provided Specs/new_specs/canonical/APEX_Execution_Logic_Detail_Spec_v1_0.md",
        "audit_id": "CANONICAL-DELETE-EXECUTION",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-DEL-CFG",
        "id": "FB-CAN-022",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Delete conflicting legacy config keys and env surfaces",
        "agent_task": "After canonical config adoption, remove superseded AppSettings/default.yaml keys and NM_* env mappings that conflict with canonical domains. Provide migration notes and fail-fast warnings for removed keys during one deprecation window, then hard-delete.",
        "affected_files": "app/config/settings.py|app/config/default.yaml|README.md|docs/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md|docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md",
        "audit_id": "CANONICAL-DELETE-CONFIG",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-DEL-DOC",
        "id": "FB-CAN-023",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Delete or archive obsolete docs/Specs canonical conflicts",
        "agent_task": "Delete or archive-as-historical conflicting docs under docs/Specs and legacy human spec narratives that contradict canonical specs. Add tombstone/redirect pages where needed so contributors cannot mistake old docs for active architecture requirements.",
        "affected_files": "docs/Specs/|docs/Human Provided Specs/|README.md|docs/",
        "docs_refs": "docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md",
        "audit_id": "CANONICAL-DELETE-DOCS",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "B",
        "batch": "CAN-DEL-TEST",
        "id": "FB-CAN-024",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Delete obsolete tests that assert legacy architecture",
        "agent_task": "Remove tests that lock in legacy DecisionPipeline/PolicySystem/hard-gate-only/thin-execution behavior after canonical replacements land. Replace with canonical domain tests in same slices to avoid temporary coverage regression.",
        "affected_files": "tests/|decision_engine/|risk_engine/|execution/",
        "docs_refs": "docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md|docs/Specs/TESTING_AND_CI.MD",
        "audit_id": "CANONICAL-DELETE-TESTS",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-CI",
        "id": "FB-CAN-025",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Add CI gates for canonical contract compliance and deletion completion",
        "agent_task": "Add CI scripts/checks that enforce canonical contract schemas, required config metadata/version fields, replay determinism checks, and hard-fail if forbidden legacy modules remain after designated cutover IDs. Ensure queue consistency gate includes canonical batch IDs.",
        "affected_files": "scripts/|.github/workflows/ci.yml|tests/|docs/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md|docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md",
        "audit_id": "CANONICAL-CI-GATES",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-REL",
        "id": "FB-CAN-026",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Implement config/version diffing and release evidence bundles",
        "agent_task": "Implement artifacts and APIs for config version diffs, logic version references, replay/shadow evidence bundles, and rollback target metadata required for release gating. Make these outputs consumable by control-plane and CI promotion checks.",
        "affected_files": "models/|orchestration/|control_plane/|scripts/|docs/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md",
        "audit_id": "CANONICAL-RELEASE-EVIDENCE",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-EXP",
        "id": "FB-CAN-027",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement experiment registry CRUD and linkage to release candidates",
        "agent_task": "Create experiment registry models/storage/APIs with required canonical fields (hypothesis, metrics-defined-before-run, failure modes, replay/scenario/shadow references, release candidate links). Enforce lifecycle transitions and traceability from experiment to promotion decision.",
        "affected_files": "research/|models/|control_plane/|docs/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Research_Experiment_Registry_Spec_v1_0.md",
        "audit_id": "CANONICAL-EXPERIMENT-REGISTRY",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-MON-ALRT",
        "id": "FB-CAN-028",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Build alert policies and dashboards for canonical domain health",
        "agent_task": "Define and implement canonical alert thresholds, routing, and dashboards for decision quality, suppressions, degradation occupancy, execution edge erosion, replay-shadow divergence, and governance anomalies. Ensure alerts are actionable and non-noisy per canonical monitoring spec.",
        "affected_files": "observability/|infra/|control_plane/|docs/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-ALERTING",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-RUNTIME",
        "id": "FB-CAN-029",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Refactor live runtime orchestration to canonical domain sequence",
        "agent_task": "Refactor app/runtime/live_service.py and shared run-step orchestration to explicit canonical sequence: normalize -> state -> structure -> trigger -> auction -> risk -> execution guidance -> intent/output -> feedback. Remove hidden coupling to legacy decision pipeline once canonical orchestrator is stable.",
        "affected_files": "app/runtime/live_service.py|decision_engine/run_step.py|decision_engine/|execution/|risk_engine/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md",
        "audit_id": "CANONICAL-RUNTIME-ORCHESTRATION",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-REPLAY-DELTA",
        "id": "FB-CAN-030",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Close live-vs-replay divergence and enforce deterministic equivalence rules",
        "agent_task": "Implement deterministic equivalence harness between live decisions and replay under identical inputs/config/logic versions, including canonical event emission and diff reports. Block promotion when divergence thresholds exceed policy.",
        "affected_files": "backtesting/|decision_engine/run_step.py|tests/|scripts/|docs/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Replay_and_Simulation_Interface_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md",
        "audit_id": "CANONICAL-LIVE-REPLAY-EQUIV",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-TRIG-MISSED",
        "id": "FB-CAN-031",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement missed-move handling and trigger false-positive memory penalties",
        "agent_task": "Implement explicit missed-move flagging and false-positive memory feedback required by canonical trigger and auction specs. Ensure missed-move suppresses ineligible candidates, and false-positive history contributes to auction penalties with deterministic replay visibility.",
        "affected_files": "decision_engine/trigger_engine.py|decision_engine/auction_engine.py|app/contracts/|backtesting/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Trigger_Math_Pseudocode_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Auction_Scoring_Constraints_Detail_Spec_v1_0.md",
        "audit_id": "CANONICAL-MISSED-MOVE",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-SIGNAL-FAM",
        "id": "FB-CAN-032",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement canonical per-signal confidence/decay families and enable flags",
        "agent_task": "Implement canonical signal confidence domain with per-family floors/caps/decay/latency/reliability parameters and feature-family enablement flags. Cover required families (funding, OI, basis, liquidation, cross-venue divergence, stablecoin proxy, execution feedback, novelty, heat components).",
        "affected_files": "app/config/|data_plane/features/|decision_engine/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md",
        "audit_id": "CANONICAL-SIGNAL-FAMILIES",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-STATE-OVR",
        "id": "FB-CAN-033",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement hard override taxonomy and degradation transition logging",
        "agent_task": "Implement explicit hard override taxonomy and degradation state transition accounting in state/risk layers, with deterministic event logging for override type, transition counts, and occupancy durations. Ensure downstream trade suppression behavior matches canonical safety semantics.",
        "affected_files": "decision_engine/state_engine.py|risk_engine/|observability/|app/contracts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_State_Regime_Logic_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-OVERRIDE-DEGRADE",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-AUCT-CORR",
        "id": "FB-CAN-034",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Add candidate correlation/thesis clustering penalties to auction",
        "agent_task": "Implement explicit candidate-correlation, overlap, and thesis-clustering penalties/constraints in auction ranking and selection caps. Include deterministic clustering metadata in decision records and replay outputs.",
        "affected_files": "decision_engine/auction_engine.py|app/contracts/|backtesting/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Auction_Scoring_Constraints_Detail_Spec_v1_0.md",
        "audit_id": "CANONICAL-AUCTION-CORRELATION",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-EXEC-FEED",
        "id": "FB-CAN-035",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement execution feedback memory into future decision quality",
        "agent_task": "Implement slow-moving execution feedback memory (realized slippage, fill ratio/latency, venue degradation) that feeds execution confidence and decision-quality penalties over time. Persist and replay this feedback deterministically.",
        "affected_files": "execution/|decision_engine/|data_plane/memory/|backtesting/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Execution_Logic_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md",
        "audit_id": "CANONICAL-EXEC-FEEDBACK",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-DEC-REC",
        "id": "FB-CAN-036",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement canonical decision record + suppression/safety event outputs",
        "agent_task": "Implement canonical output contracts for Trade Intent, Reduce Exposure Intent, No-Trade Decision, Suppression Event, Safety Override Event, and Decision Record. Ensure every no-trade path emits explicit reason codes and structured diagnostics.",
        "affected_files": "app/contracts/|decision_engine/|risk_engine/|control_plane/api.py|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Decision_Service_Feature_Schema_and_Data_Contracts_v1_0.md",
        "audit_id": "CANONICAL-DECISION-RECORD",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-FAULT",
        "id": "FB-CAN-037",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Add canonical fault injection profiles for simulation and promotion gates",
        "agent_task": "Implement fault-injection profiles (data degradation, latency stress, execution degradation) in replay/simulation and require these scenarios in release evidence bundles before promotion.",
        "affected_files": "backtesting/|orchestration/|scripts/|tests/|docs/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Replay_and_Simulation_Interface_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md",
        "audit_id": "CANONICAL-FAULT-INJECTION",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-SHADOW",
        "id": "FB-CAN-038",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Implement shadow environment comparison and promotion thresholds",
        "agent_task": "Implement explicit shadow-mode evaluation pipelines with configured divergence thresholds, probation windows, and promotion/rollback criteria. Persist comparison results as structured release evidence and expose via governance APIs.",
        "affected_files": "orchestration/|models/|control_plane/|scripts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Replay_and_Simulation_Interface_Spec_v1_0.md",
        "audit_id": "CANONICAL-SHADOW-GATING",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-MON-DRIFT",
        "id": "FB-CAN-039",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement calibration/drift monitoring families and alerts",
        "agent_task": "Implement canonical drift and calibration metrics/alerts, including realized-vs-theoretical edge erosion, confidence calibration drift, and replay-shadow divergence trend monitors with alert escalation policies.",
        "affected_files": "observability/|infra/|control_plane/|tests/|docs/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-DRIFT-MONITORING",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "CAN-DOC-GLOSS",
        "id": "FB-CAN-040",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Add canonical glossary/mapping table to eliminate ambiguous old naming",
        "agent_task": "Publish canonical glossary and old->new terminology mapping (e.g., legacy ForecastPacket/PolicySystem terms vs state/trigger/auction contracts) and enforce glossary references in docs and PR templates to reduce ambiguity during migration.",
        "affected_files": "docs/|README.md|.github/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md|docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md",
        "audit_id": "CANONICAL-GLOSSARY",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-STATE-REGIME",
        "id": "FB-CAN-041",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement full 5-class regime probability vector and transition confidence math",
        "agent_task": "Implement canonical regime vector with classes trend/range/stress/dislocated/transition, normalized probabilities, regime confidence separation metric, and transition probability computation. Ensure all downstream consumers read probability vectors (not hard labels only) and replay records full state output.",
        "affected_files": "decision_engine/state_engine.py|app/contracts/|backtesting/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_State_Regime_Logic_Detail_Spec_v1_0.md",
        "audit_id": "CANONICAL-REGIME-VECTOR",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-STATE-HEAT",
        "id": "FB-CAN-042",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement novelty/heat/reflexivity score stack and propagation",
        "agent_task": "Implement canonical novelty score, crypto heat score, and reflexivity score components with bounded normalization and propagation into trigger/auction/risk degradation penalties. Add observability distributions and replay trace fields.",
        "affected_files": "decision_engine/state_engine.py|decision_engine/trigger_engine.py|risk_engine/|observability/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_State_Regime_Logic_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-HEAT-REFLEXIVITY",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-TRIG-STAGE",
        "id": "FB-CAN-043",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement explicit Setup/Pre-Trigger/Confirm stage records and latency metrics",
        "agent_task": "Add canonical trigger-stage state machine records including setup pass, pre-trigger pass, confirm pass, stage timestamps, and setup->confirm latency metrics. Store stage failure reason codes and expose via decision records and monitoring.",
        "affected_files": "decision_engine/trigger_engine.py|app/contracts/|observability/|backtesting/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Trigger_Math_Pseudocode_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-TRIGGER-STAGES",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-AUCT-TOPN",
        "id": "FB-CAN-044",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement auction throughput bounds and top-N saturation controls",
        "agent_task": "Implement canonical auction throughput bounds: max candidate count, top-N selection caps, saturation metrics, and deterministic tie-break ordering. Add suppression reasons when candidates are excluded by throughput constraints.",
        "affected_files": "decision_engine/auction_engine.py|app/contracts/|observability/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Auction_Scoring_Constraints_Detail_Spec_v1_0.md",
        "audit_id": "CANONICAL-AUCTION-TOPN",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-RISK-SIZE",
        "id": "FB-CAN-045",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement canonical sizing formula stack (inertia, asymmetry cap, degradation multipliers)",
        "agent_task": "Implement canonical sizing stack with position inertia, capped asymmetry boosts, degradation multipliers, edge-budget scaling, and concentration-aware caps. Provide transparent intermediate terms in risk diagnostics and replay outputs.",
        "affected_files": "risk_engine/|app/contracts/risk.py|decision_engine/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md|docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md",
        "audit_id": "CANONICAL-SIZING-STACK",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-RISK-THESIS",
        "id": "FB-CAN-046",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement thesis-aware concentration and overlap risk constraints",
        "agent_task": "COMPLETED. auction_engine: RiskState.portfolio_thesis_buckets + merge_symbol_position_into_thesis_buckets; thesis overlap fraction vs apex_canonical.domains.auction.thesis_overlap_cap (hard reject thesis_overlap_cap); D_thesis boost + penalties T_ov; book exposure stress into B_edge; G_base + defense_posture when risk_liquidation_mode=defense or L_liq+stress regime dominance; clustering_metadata fb_can_046; pipeline/run_step pass current_total_exposure_usd; tests test_auction_engine FB-CAN-046.",
        "affected_files": "risk_engine/|decision_engine/auction_engine.py|app/contracts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Auction_Scoring_Constraints_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md",
        "audit_id": "CANONICAL-THESIS-RISK",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "A",
        "batch": "CAN-EXEC-STYLE",
        "id": "FB-CAN-047",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement execution style policy (passive/aggressive/staggered/twap) with urgency logic",
        "agent_task": "COMPLETED. apex_canonical.domains.execution thresholds; select_execution_style returns style_rationale_codes; ExecutionGuidance style_rationale_codes + remaining_edge + urgency_high; build_decision_record uses build_execution_guidance for trade_intent + diagnostics.execution_guidance_preview; live_service passes settings to build_execution_context_from_decision; Prometheus tb_canonical_execution_*; tests execution_logic + contracts smoke.",
        "affected_files": "execution/|app/contracts/|observability/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Execution_Logic_Detail_Spec_v1_0.md",
        "audit_id": "CANONICAL-EXEC-STYLE",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-EXEC-PFILL",
        "id": "FB-CAN-048",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement partial-fill reconciliation and residual-intent logic",
        "agent_task": "COMPLETED. app/contracts/partial_fill.py PartialFillReconciliation; execution/partial_fill_reconcile.reconcile_partial_fill_record (apex_canonical.domains.execution partial_fill_*); replay scales filled qty via scaled_order_quantity_for_fill_ratio; rows + execution_feedback_event payload partial_fill_reconciliation; tests test_partial_fill_fb_can_048.",
        "affected_files": "execution/|backtesting/|app/contracts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Execution_Logic_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Replay_and_Simulation_Interface_Spec_v1_0.md",
        "audit_id": "CANONICAL-PARTIAL-FILLS",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-DATA-STRUCT",
        "id": "FB-CAN-049",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement structural signal ingestion families (funding/OI/basis/liquidations/divergence)",
        "agent_task": "Implement/normalize structural signal ingestion families required by canonical specs: funding, open interest structure, basis/perp-spot divergence, liquidation structure, and cross-exchange divergence. Include confidence/freshness normalization and missing-data degradation behavior.",
        "affected_files": "data_plane/ingest/|data_plane/features/|app/contracts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Decision_Service_Feature_Schema_and_Data_Contracts_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_UNIFIED_Full_System_Master_Spec_v2_1_CANONICAL.md",
        "audit_id": "CANONICAL-STRUCTURAL-DATA",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-DATA-OPTIONS",
        "id": "FB-CAN-050",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement options-context and stablecoin-flow proxy feature families",
        "agent_task": "Implement optional canonical feature families for options context and stablecoin flow proxy with explicit availability rates and fallback behavior. Integrate into signal confidence domain and monitoring.",
        "affected_files": "data_plane/features/|decision_engine/|observability/|app/config/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-OPTIONS-STABLECOIN",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-GOV-OBJ",
        "id": "FB-CAN-051",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Implement release-object model (config/logic/model-family/feature-family/combined)",
        "agent_task": "Implement canonical release-object schema and APIs across config release, logic release, model-family release, feature-family release, and combined release, each with owner/rationale/evidence/rollback metadata.",
        "affected_files": "models/|orchestration/|control_plane/|app/contracts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md",
        "audit_id": "CANONICAL-RELEASE-OBJECTS",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-GOV-ENV",
        "id": "FB-CAN-052",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Implement research/simulation/shadow/live environment-stage enforcement",
        "agent_task": "Implement canonical environment-stage progression rules and enforcement so approvals are explicit per stage (research->simulation->shadow->live) with no implicit cross-stage promotion.",
        "affected_files": "orchestration/|scripts/|models/|docs/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md",
        "audit_id": "CANONICAL-ENV-STAGES",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "CAN-GOV-ROLL",
        "id": "FB-CAN-053",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Implement explicit rollback playbooks and rollback-target validation",
        "agent_task": "Implement rollback artifact validation and operator rollback playbooks linked to release objects; require rollback target references for all promotable releases and test rollback viability in CI simulation checks.",
        "affected_files": "docs/|scripts/|orchestration/|control_plane/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md|docs/RUNBOOKS.MD",
        "audit_id": "CANONICAL-ROLLBACK",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-EXP-METRICS",
        "id": "FB-CAN-054",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Enforce experiment predeclared metrics and failure-mode capture",
        "agent_task": "Add registry validators that require predeclared success metrics and failure-mode documentation before experiment completion/promotion states. Reject incomplete experiment records from promotion workflows.",
        "affected_files": "research/|models/|scripts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Research_Experiment_Registry_Spec_v1_0.md",
        "audit_id": "CANONICAL-EXPERIMENT-VALIDATION",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-REPLAY-MODES",
        "id": "FB-CAN-055",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement canonical replay modes and event-family coverage checks",
        "agent_task": "Implement replay mode enum and coverage checks for historical_nominal, historical_stress, synthetic_fault_injected, shadow_comparison, trigger_debug, execution_debug; enforce required canonical event families per run.",
        "affected_files": "backtesting/|app/contracts/|scripts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Replay_and_Simulation_Interface_Spec_v1_0.md",
        "audit_id": "CANONICAL-REPLAY-MODES",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-MON-DOMAINS",
        "id": "FB-CAN-056",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement monitoring domain coverage checklist and CI assertion",
        "agent_task": "Create machine-checkable monitoring domain checklist that asserts metric coverage across all canonical monitoring domains (system, data, state, trigger, auction, risk, execution, carry, drift, replay-shadow, governance). Fail CI when required families are absent.",
        "affected_files": "observability/|scripts/|docs/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-MONITORING-COVERAGE",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "CAN-CONFIG-DIFF",
        "id": "FB-CAN-057",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Implement immutable config diff audit trail and semantic-change guardrails",
        "agent_task": "Implement immutable config diff audit trail and semantic-change guardrails so config fields cannot silently change meaning across versions. Include diff rendering for operator review and replay compatibility checks.",
        "affected_files": "app/config/|models/|control_plane/|scripts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md",
        "audit_id": "CANONICAL-CONFIG-DIFF",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "CAN-DOC-TOMBS",
        "id": "FB-CAN-058",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Add explicit tombstone index for removed modules and removed docs",
        "agent_task": "Add docs index of removed/replaced modules/docs with removal commit links and canonical replacement pointers. Ensure operators and contributors can trace where legacy paths moved and why they were deleted.",
        "affected_files": "docs/|README.md|docs/reports/|tests/",
        "docs_refs": "docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md",
        "audit_id": "CANONICAL-TOMBSTONES",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-RUNTIME-CUT",
        "id": "FB-CAN-059",
        "kind": "hardening",
        "status": "Done",
        "summary_one_line": "Add cutover guard to prevent legacy+canonical dual-path runtime activation",
        "agent_task": "Implement runtime cutover guard that prevents simultaneous legacy and canonical execution paths after cutover phase. Fail fast on mixed-mode activation unless explicitly in migration-shadow mode with strict flags.",
        "affected_files": "app/runtime/live_service.py|decision_engine/run_step.py|app/config/|tests/",
        "docs_refs": "docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md",
        "audit_id": "CANONICAL-CUTOVER-GUARD",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "HIGH",
        "phase": "B",
        "batch": "CAN-FINAL-PRUNE",
        "id": "FB-CAN-060",
        "kind": "tech_debt",
        "status": "Done",
        "summary_one_line": "Final hard-prune: remove all deprecated canonical-migration shims",
        "agent_task": "After all canonical modules are primary and validated, remove temporary migration adapters/shims/deprecation compatibility code and any remaining old architecture remnants. This is the final hard-prune slice before declaring canonical completion.",
        "affected_files": "app/|decision_engine/|risk_engine/|execution/|backtesting/|docs/|tests/",
        "docs_refs": "docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md",
        "audit_id": "CANONICAL-FINAL-PRUNE",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-CONFIG-META",
        "id": "FB-CAN-061",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement canonical config metadata fields and validation rules",
        "agent_task": "Implement required canonical config metadata fields (config_version, config_name, created_at, created_by, environment_scope, notes, enabled_feature_families, parent version linkage). Add schema validation and migration checks to reject incomplete production configs.",
        "affected_files": "app/config/|models/|scripts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md",
        "audit_id": "CANONICAL-CONFIG-METADATA",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-CONTRACT-COMMON",
        "id": "FB-CAN-062",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Enforce canonical contract common conventions (UTC/freshness/confidence types)",
        "agent_task": "Implement contract validators for canonical common field conventions: UTC timestamps, bounded confidence/freshness normalization, semantic primitive typing, and missing/degraded data behavior rules. Add tests for malformed payload rejection and deterministic fallback behavior.",
        "affected_files": "app/contracts/|decision_engine/|data_plane/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Decision_Service_Feature_Schema_and_Data_Contracts_v1_0.md",
        "audit_id": "CANONICAL-CONTRACT-CONVENTIONS",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-SUPPRESS-TAX",
        "id": "FB-CAN-063",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement suppression/safety reason taxonomy and stable reason codes",
        "agent_task": "Define and enforce canonical suppression and safety-override reason taxonomy with stable reason codes across trigger/auction/risk/execution. Ensure all no-trade and reduction decisions emit machine-readable reasons for monitoring and replay forensic analysis.",
        "affected_files": "app/contracts/|decision_engine/|risk_engine/|execution/|observability/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Decision_Service_Feature_Schema_and_Data_Contracts_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-SUPPRESSION-TAXONOMY",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "CAN-CARRY-MON",
        "id": "FB-CAN-064",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement carry-sleeve monitoring and alert families",
        "agent_task": "Add carry-sleeve health metrics/alerts required by canonical monitoring domains, including carry exposure, carry decision quality, and carry-risk suppression indicators; integrate with dashboards and replay diagnostics.",
        "affected_files": "carry_sleeve/|observability/|infra/|control_plane/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-CARRY-MONITORING",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "CAN-GOV-MON",
        "id": "FB-CAN-065",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Implement governance/operator health monitoring domain",
        "agent_task": "Implement governance/operator monitoring metrics and alerts (promotion attempts, gate failures, rollback events, evidence completeness failures, config drift events) required by canonical monitoring spec.",
        "affected_files": "observability/|orchestration/|models/|scripts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md",
        "audit_id": "CANONICAL-GOV-MONITORING",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-EVIDENCE-SCHEMA",
        "id": "FB-CAN-066",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Define canonical evidence package schema for promotion decisions",
        "agent_task": "Define and enforce a canonical evidence package schema that links replay runs, scenario tests, shadow comparisons, key metrics, failure modes, and rollback targets for each promotion decision. Gate releases on schema completeness.",
        "affected_files": "models/|orchestration/|scripts/|docs/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Research_Experiment_Registry_Spec_v1_0.md",
        "audit_id": "CANONICAL-EVIDENCE-SCHEMA",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "CAN-CONSTANTS",
        "id": "FB-CAN-067",
        "kind": "hardening",
        "status": "Done",
        "summary_one_line": "Add guardrail against hidden magic constants in canonical paths",
        "agent_task": "Add lint/static checks and review guidance to prevent hidden constants in canonical domains; require configurable thresholds/weights to originate from canonical config versions and fail CI on newly introduced untracked constants in key modules.",
        "affected_files": "scripts/|decision_engine/|risk_engine/|execution/|app/config/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md",
        "audit_id": "CANONICAL-MAGIC-CONSTANT-GUARD",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "CAN-REPLAY-SEED",
        "id": "FB-CAN-068",
        "kind": "feature",
        "status": "Done",
        "summary_one_line": "Enforce deterministic seed and reproducibility metadata across replay/sim",
        "agent_task": "Implement deterministic seed policy and metadata persistence for replay/simulation runs, including run IDs and reproducibility hashes, so identical inputs/config/logic/seed produce identical outputs with auditable provenance.",
        "affected_files": "backtesting/|scripts/|models/|tests/|docs/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Replay_and_Simulation_Interface_Spec_v1_0.md",
        "audit_id": "CANONICAL-REPLAY-SEEDING",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "CAN-PROBATION",
        "id": "FB-CAN-069",
        "kind": "platform",
        "status": "Done",
        "summary_one_line": "Implement post-release probation-window monitors and abort triggers",
        "agent_task": "Implement canonical post-release probation monitoring with automatic abort/rollback trigger policies when divergence or risk-quality thresholds breach defined limits during early live windows.",
        "affected_files": "orchestration/|observability/|models/|scripts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-PROBATION",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-COVERAGE-MAP",
        "id": "FB-CAN-070",
        "kind": "change",
        "status": "Done",
        "summary_one_line": "Publish canonical spec section-to-queue coverage matrix and closure checklist",
        "agent_task": "Publish and maintain a machine-readable coverage matrix mapping canonical spec sections to queue IDs, implementation files, and tests. Use the matrix as the completion gate for final canonical migration sign-off.",
        "affected_files": "docs/reports/|scripts/|docs/QUEUE_STACK.csv|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/|docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md",
        "audit_id": "CANONICAL-COVERAGE-MATRIX",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-CONFIG-SNAP",
        "id": "FB-CAN-071",
        "kind": "feature",
        "status": "Open",
        "summary_one_line": "Implement canonical Service Configuration Snapshot contract",
        "agent_task": "Implement explicit service-configuration snapshot contract consumed by decision paths, including config_version, logic_version, enabled feature families, and environment scope bindings. Ensure every decision/replay record references this snapshot id for traceability.",
        "affected_files": "app/contracts/|decision_engine/|backtesting/|app/config/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Decision_Service_Feature_Schema_and_Data_Contracts_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md",
        "audit_id": "CANONICAL-CONFIG-SNAPSHOT",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-MON-LAG",
        "id": "FB-CAN-072",
        "kind": "feature",
        "status": "Open",
        "summary_one_line": "Implement processing lag/event-lag and cycle-duration monitoring details",
        "agent_task": "Add explicit processing lag, event lag, and decision-cycle duration metric families (with alert thresholds) required by canonical system-health monitoring. Include per-domain lag decomposition for data ingestion vs decision vs execution feedback.",
        "affected_files": "observability/|app/runtime/|decision_engine/|execution/|infra/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-LAG-METRICS",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "A",
        "batch": "CAN-STATE-WEEKEND",
        "id": "FB-CAN-073",
        "kind": "feature",
        "status": "Open",
        "summary_one_line": "Implement weekend/low-liquidity mode occupancy handling in state engine",
        "agent_task": "Implement weekend/low-liquidity mode occupancy and transition counters in state/regime outputs and monitoring. Propagate mode occupancy to trigger/risk aggression scaling and suppression behavior where configured.",
        "affected_files": "decision_engine/state_engine.py|risk_engine/|observability/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_State_Regime_Logic_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-WEEKEND-MODE",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "A",
        "batch": "CAN-STATE-EXRISK",
        "id": "FB-CAN-074",
        "kind": "feature",
        "status": "Open",
        "summary_one_line": "Integrate exchange-risk flags and data-integrity warnings into degradation logic",
        "agent_task": "Integrate exchange risk flags and data integrity warnings as first-class safety inputs into regime/degradation transitions and hard overrides. Emit explicit warning events and suppression reasons tied to these inputs.",
        "affected_files": "decision_engine/state_engine.py|data_plane/|risk_engine/|app/contracts/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_State_Regime_Logic_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Decision_Service_Feature_Schema_and_Data_Contracts_v1_0.md",
        "audit_id": "CANONICAL-EXCHANGE-RISK",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "A",
        "batch": "CAN-EXEC-LAT",
        "id": "FB-CAN-075",
        "kind": "feature",
        "status": "Open",
        "summary_one_line": "Implement execution latency/reliability quality terms in execution confidence",
        "agent_task": "Implement explicit latency and reliability quality terms used by execution confidence score and expose their contribution weights/config in canonical config domains. Add replay hooks for latency stress scenarios.",
        "affected_files": "execution/|app/config/|backtesting/|observability/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Execution_Logic_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Canonical_Configuration_Spec_v1_0.md",
        "audit_id": "CANONICAL-EXEC-LATENCY-QUALITY",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-EDGE-MON",
        "id": "FB-CAN-076",
        "kind": "feature",
        "status": "Open",
        "summary_one_line": "Implement edge-budget proxy monitoring and alert thresholds",
        "agent_task": "Implement edge-budget proxy metric family and alert thresholds spanning decision, auction, and execution layers, including realized-vs-theoretical edge erosion monitoring and suppression escalation when edge budget degrades.",
        "affected_files": "decision_engine/|execution/|observability/|infra/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Auction_Scoring_Constraints_Detail_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Monitoring_and_Alerting_Spec_v1_0.md",
        "audit_id": "CANONICAL-EDGE-BUDGET-MON",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "B",
        "batch": "CAN-BINDING-IMM",
        "id": "FB-CAN-077",
        "kind": "hardening",
        "status": "Open",
        "summary_one_line": "Implement immutable run-binding guard for config+logic+dataset identifiers",
        "agent_task": "Enforce immutable run binding so live/replay/shadow runs persist and expose config_version, logic_version, dataset_id, and seed identifiers with tamper-evident linkage; reject records missing mandatory identifiers.",
        "affected_files": "app/contracts/|backtesting/|orchestration/|models/|tests/",
        "docs_refs": "docs/Human Provided Specs/new_specs/canonical/APEX_Replay_and_Simulation_Interface_Spec_v1_0.md|docs/Human Provided Specs/new_specs/canonical/APEX_Config_Management_and_Release_Gating_Spec_v1_0.md",
        "audit_id": "CANONICAL-IMMUTABLE-BINDING",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "MEDIUM",
        "phase": "B",
        "batch": "CAN-FINAL-AUDIT",
        "id": "FB-CAN-078",
        "kind": "platform",
        "status": "Open",
        "summary_one_line": "Add automated canonical acceptance audit before declaring migration complete",
        "agent_task": "Add automated canonical acceptance audit script that validates queue coverage matrix completion, required module existence/deletions, contract conformance checks, and governance evidence readiness. Gate final migration closeout on this report.",
        "affected_files": "scripts/|docs/reports/|tests/|docs/QUEUE_STACK.csv",
        "docs_refs": "docs/reports/REPO_VS_CANONICAL_SPECS_GAP_AUDIT.md|docs/Human Provided Specs/new_specs/canonical/",
        "audit_id": "CANONICAL-ACCEPTANCE-AUDIT",
        "anchor": "#27-canonical-replacement-program-fb-can",
    },
    {
        "priority": "LOW",
        "phase": "D",
        "batch": "",
        "id": "_QUEUE_EMPTY_",
        "kind": "deferred",
        "status": "empty",
        "summary_one_line": "No open queue items",
        "agent_task": "N/A — add work via QUEUE.MD §6.",
        "affected_files": "",
        "docs_refs": "",
        "audit_id": "",
        "anchor": "",
    },

]


def rows_with_stack_order() -> list[dict[str, str]]:
    """Assign ``stack_order`` from list position (token-efficient: edit order, not numbers)."""
    for i, row in enumerate(ROWS):
        if (row.get("id") or "").strip() == "_QUEUE_EMPTY_" and i != len(ROWS) - 1:
            msg = "_QUEUE_EMPTY_ sentinel must be the last entry in ROWS"
            raise ValueError(msg)
    out: list[dict[str, str]] = []
    n = 0
    for row in ROWS:
        d = dict(row)
        if not (d.get("summary") or "").strip():
            d["summary"] = (d.get("summary_one_line") or "").strip()
        if (d.get("id") or "").strip() == "_QUEUE_EMPTY_":
            d["stack_order"] = "9999"
        else:
            n += 1
            d["stack_order"] = str(n)
        out.append(d)
    return out


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    path = root / "docs" / "QUEUE_STACK.csv"
    fieldnames = [
        "stack_order",
        "priority",
        "phase",
        "batch",
        "id",
        "kind",
        "status",
        "summary",
        "summary_one_line",
        "agent_task",
        "affected_files",
        "docs_refs",
        "audit_id",
        "anchor",
    ]
    rows = rows_with_stack_order()
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
        w.writeheader()
        for row in rows:
            w.writerow(row)
    print(f"Wrote {len(rows)} rows to {path}")


if __name__ == "__main__":
    main()
